//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 11/10/2024 2:18:02 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace SistemaOro.Data.Entities
{
    public partial class ComprasAdelanto : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private int _IdcomprasAdelantos;

        private string _Numcompra;

        private string _Idadelanto;

        private string? _Codcliente;

        private decimal _Sinicial;

        private decimal _Monto;

        private decimal _Sfinal;

        private DateTime _Fecha;

        private string _Codcaja;

        private string _Usuario;

        private TimeSpan _Hora;

        private string? _Codagencia;

        private int? _Codmoneda;

        private Compra _Compra;

        public ComprasAdelanto()
        {
            OnCreated();
        }

        public int IdcomprasAdelantos
        {
            get
            {
                return this._IdcomprasAdelantos;
            }
            set
            {
                if (this._IdcomprasAdelantos != value)
                {
                    this.SendPropertyChanging("IdcomprasAdelantos");
                    this._IdcomprasAdelantos = value;
                    this.SendPropertyChanged("IdcomprasAdelantos");
                }
            }
        }

        public string Numcompra
        {
            get
            {
                return this._Numcompra;
            }
            set
            {
                if (this._Numcompra != value)
                {
                    this.SendPropertyChanging("Numcompra");
                    this._Numcompra = value;
                    this.SendPropertyChanged("Numcompra");
                }
            }
        }

        public string Idadelanto
        {
            get
            {
                return this._Idadelanto;
            }
            set
            {
                if (this._Idadelanto != value)
                {
                    this.SendPropertyChanging("Idadelanto");
                    this._Idadelanto = value;
                    this.SendPropertyChanged("Idadelanto");
                }
            }
        }

        public string? Codcliente
        {
            get
            {
                return this._Codcliente;
            }
            set
            {
                if (this._Codcliente != value)
                {
                    this.SendPropertyChanging("Codcliente");
                    this._Codcliente = value;
                    this.SendPropertyChanged("Codcliente");
                }
            }
        }

        public decimal Sinicial
        {
            get
            {
                return this._Sinicial;
            }
            set
            {
                if (this._Sinicial != value)
                {
                    this.SendPropertyChanging("Sinicial");
                    this._Sinicial = value;
                    this.SendPropertyChanged("Sinicial");
                }
            }
        }

        public decimal Monto
        {
            get
            {
                return this._Monto;
            }
            set
            {
                if (this._Monto != value)
                {
                    this.SendPropertyChanging("Monto");
                    this._Monto = value;
                    this.SendPropertyChanged("Monto");
                }
            }
        }

        public decimal Sfinal
        {
            get
            {
                return this._Sfinal;
            }
            set
            {
                if (this._Sfinal != value)
                {
                    this.SendPropertyChanging("Sfinal");
                    this._Sfinal = value;
                    this.SendPropertyChanged("Sfinal");
                }
            }
        }

        public DateTime Fecha
        {
            get
            {
                return this._Fecha;
            }
            set
            {
                if (this._Fecha != value)
                {
                    this.SendPropertyChanging("Fecha");
                    this._Fecha = value;
                    this.SendPropertyChanged("Fecha");
                }
            }
        }

        public string Codcaja
        {
            get
            {
                return this._Codcaja;
            }
            set
            {
                if (this._Codcaja != value)
                {
                    this.SendPropertyChanging("Codcaja");
                    this._Codcaja = value;
                    this.SendPropertyChanged("Codcaja");
                }
            }
        }

        public string Usuario
        {
            get
            {
                return this._Usuario;
            }
            set
            {
                if (this._Usuario != value)
                {
                    this.SendPropertyChanging("Usuario");
                    this._Usuario = value;
                    this.SendPropertyChanged("Usuario");
                }
            }
        }

        public TimeSpan Hora
        {
            get
            {
                return this._Hora;
            }
            set
            {
                if (this._Hora != value)
                {
                    this.SendPropertyChanging("Hora");
                    this._Hora = value;
                    this.SendPropertyChanged("Hora");
                }
            }
        }

        public string? Codagencia
        {
            get
            {
                return this._Codagencia;
            }
            set
            {
                if (this._Codagencia != value)
                {
                    this.SendPropertyChanging("Codagencia");
                    this._Codagencia = value;
                    this.SendPropertyChanged("Codagencia");
                }
            }
        }

        public int? Codmoneda
        {
            get
            {
                return this._Codmoneda;
            }
            set
            {
                if (this._Codmoneda != value)
                {
                    this.SendPropertyChanging("Codmoneda");
                    this._Codmoneda = value;
                    this.SendPropertyChanged("Codmoneda");
                }
            }
        }

        public virtual Compra Compra
        {
            get
            {
                return this._Compra;
            }
            set
            {
                if (this._Compra != value)
                {
                    this.SendPropertyChanging("Compra");
                    this._Compra = value;
                    this.SendPropertyChanged("Compra");
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
