//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 27/11/2024 2:58:43 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace SistemaOro.Data.Entities
{
    public partial class Mcaja : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private int _Idcaja;

        private string _Codcaja;

        private string? _Codagencia;

        private DateTime? _Fecha;

        private decimal? _Sinicial;

        private decimal? _Entrada;

        private decimal? _Salida;

        private decimal? _Sfinal;

        private int? _Estado;

        private IList<Detacaja> _Detacajas;

        private Agencia _Agencia;

        private Caja _Caja;

        public Mcaja()
        {
            this._Detacajas = new List<Detacaja>();
            OnCreated();
        }

        public int Idcaja
        {
            get
            {
                return this._Idcaja;
            }
            set
            {
                if (this._Idcaja != value)
                {
                    this.SendPropertyChanging("Idcaja");
                    this._Idcaja = value;
                    this.SendPropertyChanged("Idcaja");
                }
            }
        }

        public string Codcaja
        {
            get
            {
                return this._Codcaja;
            }
            set
            {
                if (this._Codcaja != value)
                {
                    this.SendPropertyChanging("Codcaja");
                    this._Codcaja = value;
                    this.SendPropertyChanged("Codcaja");
                }
            }
        }

        public string? Codagencia
        {
            get
            {
                return this._Codagencia;
            }
            set
            {
                if (this._Codagencia != value)
                {
                    this.SendPropertyChanging("Codagencia");
                    this._Codagencia = value;
                    this.SendPropertyChanged("Codagencia");
                }
            }
        }

        public DateTime? Fecha
        {
            get
            {
                return this._Fecha;
            }
            set
            {
                if (this._Fecha != value)
                {
                    this.SendPropertyChanging("Fecha");
                    this._Fecha = value;
                    this.SendPropertyChanged("Fecha");
                }
            }
        }

        public decimal? Sinicial
        {
            get
            {
                return this._Sinicial;
            }
            set
            {
                if (this._Sinicial != value)
                {
                    this.SendPropertyChanging("Sinicial");
                    this._Sinicial = value;
                    this.SendPropertyChanged("Sinicial");
                }
            }
        }

        public decimal? Entrada
        {
            get
            {
                return this._Entrada;
            }
            set
            {
                if (this._Entrada != value)
                {
                    this.SendPropertyChanging("Entrada");
                    this._Entrada = value;
                    this.SendPropertyChanged("Entrada");
                }
            }
        }

        public decimal? Salida
        {
            get
            {
                return this._Salida;
            }
            set
            {
                if (this._Salida != value)
                {
                    this.SendPropertyChanging("Salida");
                    this._Salida = value;
                    this.SendPropertyChanged("Salida");
                }
            }
        }

        public decimal? Sfinal
        {
            get
            {
                return this._Sfinal;
            }
            set
            {
                if (this._Sfinal != value)
                {
                    this.SendPropertyChanging("Sfinal");
                    this._Sfinal = value;
                    this.SendPropertyChanged("Sfinal");
                }
            }
        }

        public int? Estado
        {
            get
            {
                return this._Estado;
            }
            set
            {
                if (this._Estado != value)
                {
                    this.SendPropertyChanging("Estado");
                    this._Estado = value;
                    this.SendPropertyChanged("Estado");
                }
            }
        }

        public virtual IList<Detacaja> Detacajas
        {
            get
            {
                return this._Detacajas;
            }
            set
            {
                this._Detacajas = value;
            }
        }

        public virtual Agencia Agencia
        {
            get
            {
                return this._Agencia;
            }
            set
            {
                if (this._Agencia != value)
                {
                    this.SendPropertyChanging("Agencia");
                    this._Agencia = value;
                    this.SendPropertyChanged("Agencia");
                }
            }
        }

        public virtual Caja Caja
        {
            get
            {
                return this._Caja;
            }
            set
            {
                if (this._Caja != value)
                {
                    this.SendPropertyChanging("Caja");
                    this._Caja = value;
                    this.SendPropertyChanged("Caja");
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
