//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 30/12/2024 11:10:27 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace SistemaOro.Data.Entities
{
    public partial class Rubro : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private int _Codrubro;

        private string _Descrubro;

        private int? _Naturaleza;

        private IList<Movcaja> _Movcajas;

        public Rubro()
        {
            this._Movcajas = new List<Movcaja>();
            OnCreated();
        }

        public int Codrubro
        {
            get
            {
                return this._Codrubro;
            }
            set
            {
                if (this._Codrubro != value)
                {
                    this.SendPropertyChanging("Codrubro");
                    this._Codrubro = value;
                    this.SendPropertyChanged("Codrubro");
                }
            }
        }

        public string Descrubro
        {
            get
            {
                return this._Descrubro;
            }
            set
            {
                if (this._Descrubro != value)
                {
                    this.SendPropertyChanging("Descrubro");
                    this._Descrubro = value;
                    this.SendPropertyChanged("Descrubro");
                }
            }
        }

        public int? Naturaleza
        {
            get
            {
                return this._Naturaleza;
            }
            set
            {
                if (this._Naturaleza != value)
                {
                    this.SendPropertyChanging("Naturaleza");
                    this._Naturaleza = value;
                    this.SendPropertyChanged("Naturaleza");
                }
            }
        }

        public virtual IList<Movcaja> Movcajas
        {
            get
            {
                return this._Movcajas;
            }
            set
            {
                this._Movcajas = value;
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
