//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 28/9/2024 10:53:19 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace SistemaOro.Data.Entities
{
    public partial class TipoCambio : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private DateTime _Fecha;

        private decimal _Tipocambio;

        private string? _Hora;

        private decimal? _PrecioOro;

        public TipoCambio()
        {
            OnCreated();
        }

        public DateTime Fecha
        {
            get
            {
                return this._Fecha;
            }
            set
            {
                if (this._Fecha != value)
                {
                    this.SendPropertyChanging("Fecha");
                    this._Fecha = value;
                    this.SendPropertyChanged("Fecha");
                }
            }
        }

        public decimal Tipocambio
        {
            get
            {
                return this._Tipocambio;
            }
            set
            {
                if (this._Tipocambio != value)
                {
                    this.SendPropertyChanging("Tipocambio");
                    this._Tipocambio = value;
                    this.SendPropertyChanged("Tipocambio");
                }
            }
        }

        public string? Hora
        {
            get
            {
                return this._Hora;
            }
            set
            {
                if (this._Hora != value)
                {
                    this.SendPropertyChanging("Hora");
                    this._Hora = value;
                    this.SendPropertyChanged("Hora");
                }
            }
        }

        public decimal? PrecioOro
        {
            get
            {
                return this._PrecioOro;
            }
            set
            {
                if (this._PrecioOro != value)
                {
                    this.SendPropertyChanging("PrecioOro");
                    this._PrecioOro = value;
                    this.SendPropertyChanged("PrecioOro");
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
