//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 28/7/2024 4:09:42 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace SistemaOro.Data.Entities
{
    public partial class Compra {

        public Compra()
        {
            this.SaldoAdelanto = 0m;
            OnCreated();
        }

        public string Numcompra { get; set; }

        public string Codagencia { get; set; }

        public string Codcliente { get; set; }

        public string Codcaja { get; set; }

        public decimal Peso { get; set; }

        public int Codmoneda { get; set; }

        public decimal Total { get; set; }

        public DateTime Fecha { get; set; }

        public EstadoCompra Codestado { get; set; }

        public string Usuario { get; set; }

        public string Hora { get; set; }

        public string FormaPago { get; set; }

        public int Dgnumdes { get; set; }

        public decimal Efectivo { get; set; }

        public decimal Cheque { get; set; }

        public decimal Transferencia { get; set; }

        public decimal PorCobrar { get; set; }

        public decimal PorPagar { get; set; }

        public decimal Adelantos { get; set; }

        public decimal SaldoPorPagar { get; set; }

        public decimal? SaldoAdelanto { get; set; }

        public decimal? SaldoAdelantoDolares { get; set; }

        public int? Nocontrato { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
