//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 29/4/2024 02:55 p. m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace SistemaOro.Data.Entities
{
    public partial class DescargueByCompra {

        public DescargueByCompra()
        {
            OnCreated();
        }

        public int Dgnumdes { get; set; }

        public DateTime Dgfecdes { get; set; }

        public string Numcompra { get; set; }

        public DateTime Fecha { get; set; }

        public string Codcliente { get; set; }

        public string Nombres { get; set; }

        public string? Apellidos { get; set; }

        public decimal Peso { get; set; }

        public decimal Total { get; set; }

        public int Cantcompra { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
