//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 13/4/2024 12:33 p. m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace SistemaOro.Data.Entities
{
    public partial class Agencia {

        public Agencia()
        {
            this.Compras = new List<Compra>();
            this.ComprasAdelantos = new List<ComprasAdelanto>();
            this.DetCompras = new List<DetCompra>();
            this.Detacierres = new List<Detacierre>();
            this.Mcajas = new List<Mcaja>();
            OnCreated();
        }

        public string Codagencia { get; set; }

        public string Nomagencia { get; set; }

        public string Diragencia { get; set; }

        public string Disagencia { get; set; }

        public string Telagencia { get; set; }

        public int? Numcompra { get; set; }

        public virtual IList<Compra> Compras { get; set; }

        public virtual IList<ComprasAdelanto> ComprasAdelantos { get; set; }

        public virtual IList<DetCompra> DetCompras { get; set; }

        public virtual IList<Detacierre> Detacierres { get; set; }

        public virtual IList<Mcaja> Mcajas { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
