//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 27/7/2025 7:04:52 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace SistemaOro.Data.Entities
{
    public partial class MovimientosCajaSelect : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private string? _Caja;

        private string _Descripcion;

        private string _Hora1;

        private DateTime _Fecha1;

        private string? _Referencia;

        private string? _Concepto1;

        private decimal? _Cheque;

        private decimal? _Efectivo1;

        private decimal? _Transferencia1;

        private decimal? _ChequeExt;

        private string? _Simbolo;

        private int _IdDetaCaja;

        private decimal? _EfectivoExt;

        private string? _Usuario;

        private decimal? _TransferenciaExt;

        private decimal? _Sinicial;

        private decimal? _SinicialExt;

        private decimal? _Entrada;

        private decimal? _EntradaExt;

        private decimal? _Salida;

        private decimal? _SalidaExt;

        private decimal? _Sfinal;

        private decimal? _SfinalExt;

        public MovimientosCajaSelect()
        {
            OnCreated();
        }

        public string? Caja
        {
            get
            {
                return this._Caja;
            }
            set
            {
                if (this._Caja != value)
                {
                    this.SendPropertyChanging("Caja");
                    this._Caja = value;
                    this.SendPropertyChanged("Caja");
                }
            }
        }

        public string Descripcion
        {
            get
            {
                return this._Descripcion;
            }
            set
            {
                if (this._Descripcion != value)
                {
                    this.SendPropertyChanging("Descripcion");
                    this._Descripcion = value;
                    this.SendPropertyChanged("Descripcion");
                }
            }
        }

        public string Hora1
        {
            get
            {
                return this._Hora1;
            }
            set
            {
                if (this._Hora1 != value)
                {
                    this.SendPropertyChanging("Hora1");
                    this._Hora1 = value;
                    this.SendPropertyChanged("Hora1");
                }
            }
        }

        public DateTime Fecha1
        {
            get
            {
                return this._Fecha1;
            }
            set
            {
                if (this._Fecha1 != value)
                {
                    this.SendPropertyChanging("Fecha1");
                    this._Fecha1 = value;
                    this.SendPropertyChanged("Fecha1");
                }
            }
        }

        public string? Referencia
        {
            get
            {
                return this._Referencia;
            }
            set
            {
                if (this._Referencia != value)
                {
                    this.SendPropertyChanging("Referencia");
                    this._Referencia = value;
                    this.SendPropertyChanged("Referencia");
                }
            }
        }

        public string? Concepto1
        {
            get
            {
                return this._Concepto1;
            }
            set
            {
                if (this._Concepto1 != value)
                {
                    this.SendPropertyChanging("Concepto1");
                    this._Concepto1 = value;
                    this.SendPropertyChanged("Concepto1");
                }
            }
        }

        public decimal? Cheque
        {
            get
            {
                return this._Cheque;
            }
            set
            {
                if (this._Cheque != value)
                {
                    this.SendPropertyChanging("Cheque");
                    this._Cheque = value;
                    this.SendPropertyChanged("Cheque");
                }
            }
        }

        public decimal? Efectivo1
        {
            get
            {
                return this._Efectivo1;
            }
            set
            {
                if (this._Efectivo1 != value)
                {
                    this.SendPropertyChanging("Efectivo1");
                    this._Efectivo1 = value;
                    this.SendPropertyChanged("Efectivo1");
                }
            }
        }

        public decimal? Transferencia1
        {
            get
            {
                return this._Transferencia1;
            }
            set
            {
                if (this._Transferencia1 != value)
                {
                    this.SendPropertyChanging("Transferencia1");
                    this._Transferencia1 = value;
                    this.SendPropertyChanged("Transferencia1");
                }
            }
        }

        public decimal? ChequeExt
        {
            get
            {
                return this._ChequeExt;
            }
            set
            {
                if (this._ChequeExt != value)
                {
                    this.SendPropertyChanging("ChequeExt");
                    this._ChequeExt = value;
                    this.SendPropertyChanged("ChequeExt");
                }
            }
        }

        public string? Simbolo
        {
            get
            {
                return this._Simbolo;
            }
            set
            {
                if (this._Simbolo != value)
                {
                    this.SendPropertyChanging("Simbolo");
                    this._Simbolo = value;
                    this.SendPropertyChanged("Simbolo");
                }
            }
        }

        public int IdDetaCaja
        {
            get
            {
                return this._IdDetaCaja;
            }
            set
            {
                if (this._IdDetaCaja != value)
                {
                    this.SendPropertyChanging("IdDetaCaja");
                    this._IdDetaCaja = value;
                    this.SendPropertyChanged("IdDetaCaja");
                }
            }
        }

        public decimal? EfectivoExt
        {
            get
            {
                return this._EfectivoExt;
            }
            set
            {
                if (this._EfectivoExt != value)
                {
                    this.SendPropertyChanging("EfectivoExt");
                    this._EfectivoExt = value;
                    this.SendPropertyChanged("EfectivoExt");
                }
            }
        }

        public string? Usuario
        {
            get
            {
                return this._Usuario;
            }
            set
            {
                if (this._Usuario != value)
                {
                    this.SendPropertyChanging("Usuario");
                    this._Usuario = value;
                    this.SendPropertyChanged("Usuario");
                }
            }
        }

        public decimal? TransferenciaExt
        {
            get
            {
                return this._TransferenciaExt;
            }
            set
            {
                if (this._TransferenciaExt != value)
                {
                    this.SendPropertyChanging("TransferenciaExt");
                    this._TransferenciaExt = value;
                    this.SendPropertyChanged("TransferenciaExt");
                }
            }
        }

        public decimal? Sinicial
        {
            get
            {
                return this._Sinicial;
            }
            set
            {
                if (this._Sinicial != value)
                {
                    this.SendPropertyChanging("Sinicial");
                    this._Sinicial = value;
                    this.SendPropertyChanged("Sinicial");
                }
            }
        }

        public decimal? SinicialExt
        {
            get
            {
                return this._SinicialExt;
            }
            set
            {
                if (this._SinicialExt != value)
                {
                    this.SendPropertyChanging("SinicialExt");
                    this._SinicialExt = value;
                    this.SendPropertyChanged("SinicialExt");
                }
            }
        }

        public decimal? Entrada
        {
            get
            {
                return this._Entrada;
            }
            set
            {
                if (this._Entrada != value)
                {
                    this.SendPropertyChanging("Entrada");
                    this._Entrada = value;
                    this.SendPropertyChanged("Entrada");
                }
            }
        }

        public decimal? EntradaExt
        {
            get
            {
                return this._EntradaExt;
            }
            set
            {
                if (this._EntradaExt != value)
                {
                    this.SendPropertyChanging("EntradaExt");
                    this._EntradaExt = value;
                    this.SendPropertyChanged("EntradaExt");
                }
            }
        }

        public decimal? Salida
        {
            get
            {
                return this._Salida;
            }
            set
            {
                if (this._Salida != value)
                {
                    this.SendPropertyChanging("Salida");
                    this._Salida = value;
                    this.SendPropertyChanged("Salida");
                }
            }
        }

        public decimal? SalidaExt
        {
            get
            {
                return this._SalidaExt;
            }
            set
            {
                if (this._SalidaExt != value)
                {
                    this.SendPropertyChanging("SalidaExt");
                    this._SalidaExt = value;
                    this.SendPropertyChanged("SalidaExt");
                }
            }
        }

        public decimal? Sfinal
        {
            get
            {
                return this._Sfinal;
            }
            set
            {
                if (this._Sfinal != value)
                {
                    this.SendPropertyChanging("Sfinal");
                    this._Sfinal = value;
                    this.SendPropertyChanged("Sfinal");
                }
            }
        }

        public decimal? SfinalExt
        {
            get
            {
                return this._SfinalExt;
            }
            set
            {
                if (this._SfinalExt != value)
                {
                    this.SendPropertyChanging("SfinalExt");
                    this._SfinalExt = value;
                    this.SendPropertyChanged("SfinalExt");
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
