//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 25/11/2024 4:19:40 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace SistemaOro.Data.Entities
{
    public partial class Compra : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private string _Numcompra;

        private string _Codagencia;

        private string _Codcliente;

        private string _Codcaja;

        private decimal _Peso;

        private int _Codmoneda;

        private decimal _Total;

        private DateTime _Fecha;

        private EstadoCompra _Codestado;

        private string _Usuario;

        private string _Hora;

        private string _FormaPago;

        private int? _Dgnumdes;

        private decimal _Efectivo;

        private decimal _Cheque;

        private decimal _Transferencia;

        private decimal _PorCobrar;

        private decimal _PorPagar;

        private decimal _Adelantos;

        private decimal _SaldoPorPagar;

        private decimal? _SaldoAdelanto;

        private decimal? _SaldoAdelantoDolares;

        private int? _Nocontrato;

        private decimal? _Subtotal;

        private decimal? _Descuento;

        private int? _IdTipoPrecio;

        private IList<Adelanto> _Adelantos1;

        private Cliente _Cliente;

        private Moneda _Moneda;

        private Agencia _Agencia;

        private Usuario _Usuario1;

        private Caja _Caja;

        private Descargue _Descargue;

        private IList<ComprasAdelanto> _ComprasAdelantos;

        private IList<DetCompra> _DetCompras;

        private TipoPrecio _TipoPrecio;

        public Compra()
        {
            this._Dgnumdes = 0;
            this._SaldoAdelanto = 0m;
            this._Adelantos1 = new List<Adelanto>();
            this._ComprasAdelantos = new List<ComprasAdelanto>();
            this._DetCompras = new List<DetCompra>();
            OnCreated();
        }

        public string Numcompra
        {
            get
            {
                return this._Numcompra;
            }
            set
            {
                if (this._Numcompra != value)
                {
                    this.SendPropertyChanging("Numcompra");
                    this._Numcompra = value;
                    this.SendPropertyChanged("Numcompra");
                }
            }
        }

        public string Codagencia
        {
            get
            {
                return this._Codagencia;
            }
            set
            {
                if (this._Codagencia != value)
                {
                    this.SendPropertyChanging("Codagencia");
                    this._Codagencia = value;
                    this.SendPropertyChanged("Codagencia");
                }
            }
        }

        public string Codcliente
        {
            get
            {
                return this._Codcliente;
            }
            set
            {
                if (this._Codcliente != value)
                {
                    this.SendPropertyChanging("Codcliente");
                    this._Codcliente = value;
                    this.SendPropertyChanged("Codcliente");
                }
            }
        }

        public string Codcaja
        {
            get
            {
                return this._Codcaja;
            }
            set
            {
                if (this._Codcaja != value)
                {
                    this.SendPropertyChanging("Codcaja");
                    this._Codcaja = value;
                    this.SendPropertyChanged("Codcaja");
                }
            }
        }

        public decimal Peso
        {
            get
            {
                return this._Peso;
            }
            set
            {
                if (this._Peso != value)
                {
                    this.SendPropertyChanging("Peso");
                    this._Peso = value;
                    this.SendPropertyChanged("Peso");
                }
            }
        }

        public int Codmoneda
        {
            get
            {
                return this._Codmoneda;
            }
            set
            {
                if (this._Codmoneda != value)
                {
                    this.SendPropertyChanging("Codmoneda");
                    this._Codmoneda = value;
                    this.SendPropertyChanged("Codmoneda");
                }
            }
        }

        public decimal Total
        {
            get
            {
                return this._Total;
            }
            set
            {
                if (this._Total != value)
                {
                    this.SendPropertyChanging("Total");
                    this._Total = value;
                    this.SendPropertyChanged("Total");
                }
            }
        }

        public DateTime Fecha
        {
            get
            {
                return this._Fecha;
            }
            set
            {
                if (this._Fecha != value)
                {
                    this.SendPropertyChanging("Fecha");
                    this._Fecha = value;
                    this.SendPropertyChanged("Fecha");
                }
            }
        }

        public EstadoCompra Codestado
        {
            get
            {
                return this._Codestado;
            }
            set
            {
                if (this._Codestado != value)
                {
                    this.SendPropertyChanging("Codestado");
                    this._Codestado = value;
                    this.SendPropertyChanged("Codestado");
                }
            }
        }

        public string Usuario
        {
            get
            {
                return this._Usuario;
            }
            set
            {
                if (this._Usuario != value)
                {
                    this.SendPropertyChanging("Usuario");
                    this._Usuario = value;
                    this.SendPropertyChanged("Usuario");
                }
            }
        }

        public string Hora
        {
            get
            {
                return this._Hora;
            }
            set
            {
                if (this._Hora != value)
                {
                    this.SendPropertyChanging("Hora");
                    this._Hora = value;
                    this.SendPropertyChanged("Hora");
                }
            }
        }

        public string FormaPago
        {
            get
            {
                return this._FormaPago;
            }
            set
            {
                if (this._FormaPago != value)
                {
                    this.SendPropertyChanging("FormaPago");
                    this._FormaPago = value;
                    this.SendPropertyChanged("FormaPago");
                }
            }
        }

        public int? Dgnumdes
        {
            get
            {
                return this._Dgnumdes;
            }
            set
            {
                if (this._Dgnumdes != value)
                {
                    this.SendPropertyChanging("Dgnumdes");
                    this._Dgnumdes = value;
                    this.SendPropertyChanged("Dgnumdes");
                }
            }
        }

        public decimal Efectivo
        {
            get
            {
                return this._Efectivo;
            }
            set
            {
                if (this._Efectivo != value)
                {
                    this.SendPropertyChanging("Efectivo");
                    this._Efectivo = value;
                    this.SendPropertyChanged("Efectivo");
                }
            }
        }

        public decimal Cheque
        {
            get
            {
                return this._Cheque;
            }
            set
            {
                if (this._Cheque != value)
                {
                    this.SendPropertyChanging("Cheque");
                    this._Cheque = value;
                    this.SendPropertyChanged("Cheque");
                }
            }
        }

        public decimal Transferencia
        {
            get
            {
                return this._Transferencia;
            }
            set
            {
                if (this._Transferencia != value)
                {
                    this.SendPropertyChanging("Transferencia");
                    this._Transferencia = value;
                    this.SendPropertyChanged("Transferencia");
                }
            }
        }

        public decimal PorCobrar
        {
            get
            {
                return this._PorCobrar;
            }
            set
            {
                if (this._PorCobrar != value)
                {
                    this.SendPropertyChanging("PorCobrar");
                    this._PorCobrar = value;
                    this.SendPropertyChanged("PorCobrar");
                }
            }
        }

        public decimal PorPagar
        {
            get
            {
                return this._PorPagar;
            }
            set
            {
                if (this._PorPagar != value)
                {
                    this.SendPropertyChanging("PorPagar");
                    this._PorPagar = value;
                    this.SendPropertyChanged("PorPagar");
                }
            }
        }

        public decimal Adelantos
        {
            get
            {
                return this._Adelantos;
            }
            set
            {
                if (this._Adelantos != value)
                {
                    this.SendPropertyChanging("Adelantos");
                    this._Adelantos = value;
                    this.SendPropertyChanged("Adelantos");
                }
            }
        }

        public decimal SaldoPorPagar
        {
            get
            {
                return this._SaldoPorPagar;
            }
            set
            {
                if (this._SaldoPorPagar != value)
                {
                    this.SendPropertyChanging("SaldoPorPagar");
                    this._SaldoPorPagar = value;
                    this.SendPropertyChanged("SaldoPorPagar");
                }
            }
        }

        public decimal? SaldoAdelanto
        {
            get
            {
                return this._SaldoAdelanto;
            }
            set
            {
                if (this._SaldoAdelanto != value)
                {
                    this.SendPropertyChanging("SaldoAdelanto");
                    this._SaldoAdelanto = value;
                    this.SendPropertyChanged("SaldoAdelanto");
                }
            }
        }

        public decimal? SaldoAdelantoDolares
        {
            get
            {
                return this._SaldoAdelantoDolares;
            }
            set
            {
                if (this._SaldoAdelantoDolares != value)
                {
                    this.SendPropertyChanging("SaldoAdelantoDolares");
                    this._SaldoAdelantoDolares = value;
                    this.SendPropertyChanged("SaldoAdelantoDolares");
                }
            }
        }

        public int? Nocontrato
        {
            get
            {
                return this._Nocontrato;
            }
            set
            {
                if (this._Nocontrato != value)
                {
                    this.SendPropertyChanging("Nocontrato");
                    this._Nocontrato = value;
                    this.SendPropertyChanged("Nocontrato");
                }
            }
        }

        public decimal? Subtotal
        {
            get
            {
                return this._Subtotal;
            }
            set
            {
                if (this._Subtotal != value)
                {
                    this.SendPropertyChanging("Subtotal");
                    this._Subtotal = value;
                    this.SendPropertyChanged("Subtotal");
                }
            }
        }

        public decimal? Descuento
        {
            get
            {
                return this._Descuento;
            }
            set
            {
                if (this._Descuento != value)
                {
                    this.SendPropertyChanging("Descuento");
                    this._Descuento = value;
                    this.SendPropertyChanged("Descuento");
                }
            }
        }

        public int? IdTipoPrecio
        {
            get
            {
                return this._IdTipoPrecio;
            }
            set
            {
                if (this._IdTipoPrecio != value)
                {
                    this.SendPropertyChanging("IdTipoPrecio");
                    this._IdTipoPrecio = value;
                    this.SendPropertyChanged("IdTipoPrecio");
                }
            }
        }

        public virtual IList<Adelanto> Adelantos1
        {
            get
            {
                return this._Adelantos1;
            }
            set
            {
                this._Adelantos1 = value;
            }
        }

        public virtual Cliente Cliente
        {
            get
            {
                return this._Cliente;
            }
            set
            {
                if (this._Cliente != value)
                {
                    this.SendPropertyChanging("Cliente");
                    this._Cliente = value;
                    this.SendPropertyChanged("Cliente");
                }
            }
        }

        public virtual Moneda Moneda
        {
            get
            {
                return this._Moneda;
            }
            set
            {
                if (this._Moneda != value)
                {
                    this.SendPropertyChanging("Moneda");
                    this._Moneda = value;
                    this.SendPropertyChanged("Moneda");
                }
            }
        }

        public virtual Agencia Agencia
        {
            get
            {
                return this._Agencia;
            }
            set
            {
                if (this._Agencia != value)
                {
                    this.SendPropertyChanging("Agencia");
                    this._Agencia = value;
                    this.SendPropertyChanged("Agencia");
                }
            }
        }

        public virtual Usuario Usuario1
        {
            get
            {
                return this._Usuario1;
            }
            set
            {
                if (this._Usuario1 != value)
                {
                    this.SendPropertyChanging("Usuario1");
                    this._Usuario1 = value;
                    this.SendPropertyChanged("Usuario1");
                }
            }
        }

        public virtual Caja Caja
        {
            get
            {
                return this._Caja;
            }
            set
            {
                if (this._Caja != value)
                {
                    this.SendPropertyChanging("Caja");
                    this._Caja = value;
                    this.SendPropertyChanged("Caja");
                }
            }
        }

        public virtual Descargue Descargue
        {
            get
            {
                return this._Descargue;
            }
            set
            {
                if (this._Descargue != value)
                {
                    this.SendPropertyChanging("Descargue");
                    this._Descargue = value;
                    this.SendPropertyChanged("Descargue");
                }
            }
        }

        public virtual IList<ComprasAdelanto> ComprasAdelantos
        {
            get
            {
                return this._ComprasAdelantos;
            }
            set
            {
                this._ComprasAdelantos = value;
            }
        }

        public virtual IList<DetCompra> DetCompras
        {
            get
            {
                return this._DetCompras;
            }
            set
            {
                this._DetCompras = value;
            }
        }

        public virtual TipoPrecio TipoPrecio
        {
            get
            {
                return this._TipoPrecio;
            }
            set
            {
                if (this._TipoPrecio != value)
                {
                    this.SendPropertyChanging("TipoPrecio");
                    this._TipoPrecio = value;
                    this.SendPropertyChanged("TipoPrecio");
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
