//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 27/7/2025 7:04:52 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace SistemaOro.Data.Entities
{
    public partial class DetCompra : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private int _Idetacompra;

        private string _Numcompra;

        private int _Linea;

        private string _Descripcion;

        private string _Kilate;

        private decimal _Preciok;

        private decimal _Peso;

        private decimal? _Importe;

        private string? _Kilshowdoc;

        private int? _Numdescargue;

        private string? _Codagencia;

        private DateTime? _Fecha;

        private int? _Lectura;

        private Compra _Compra;

        public DetCompra()
        {
            this._Numdescargue = 0;
            OnCreated();
        }

        public int Idetacompra
        {
            get
            {
                return this._Idetacompra;
            }
            set
            {
                if (this._Idetacompra != value)
                {
                    this.SendPropertyChanging("Idetacompra");
                    this._Idetacompra = value;
                    this.SendPropertyChanged("Idetacompra");
                }
            }
        }

        public string Numcompra
        {
            get
            {
                return this._Numcompra;
            }
            set
            {
                if (this._Numcompra != value)
                {
                    this.SendPropertyChanging("Numcompra");
                    this._Numcompra = value;
                    this.SendPropertyChanged("Numcompra");
                }
            }
        }

        public int Linea
        {
            get
            {
                return this._Linea;
            }
            set
            {
                if (this._Linea != value)
                {
                    this.SendPropertyChanging("Linea");
                    this._Linea = value;
                    this.SendPropertyChanged("Linea");
                }
            }
        }

        public string Descripcion
        {
            get
            {
                return this._Descripcion;
            }
            set
            {
                if (this._Descripcion != value)
                {
                    this.SendPropertyChanging("Descripcion");
                    this._Descripcion = value;
                    this.SendPropertyChanged("Descripcion");
                }
            }
        }

        public string Kilate
        {
            get
            {
                return this._Kilate;
            }
            set
            {
                if (this._Kilate != value)
                {
                    this.SendPropertyChanging("Kilate");
                    this._Kilate = value;
                    this.SendPropertyChanged("Kilate");
                }
            }
        }

        public decimal Preciok
        {
            get
            {
                return this._Preciok;
            }
            set
            {
                if (this._Preciok != value)
                {
                    this.SendPropertyChanging("Preciok");
                    this._Preciok = value;
                    this.SendPropertyChanged("Preciok");
                }
            }
        }

        public decimal Peso
        {
            get
            {
                return this._Peso;
            }
            set
            {
                if (this._Peso != value)
                {
                    this.SendPropertyChanging("Peso");
                    this._Peso = value;
                    this.SendPropertyChanged("Peso");
                }
            }
        }

        public decimal? Importe
        {
            get
            {
                return this._Importe;
            }
            set
            {
                if (this._Importe != value)
                {
                    this.SendPropertyChanging("Importe");
                    this._Importe = value;
                    this.SendPropertyChanged("Importe");
                }
            }
        }

        public string? Kilshowdoc
        {
            get
            {
                return this._Kilshowdoc;
            }
            set
            {
                if (this._Kilshowdoc != value)
                {
                    this.SendPropertyChanging("Kilshowdoc");
                    this._Kilshowdoc = value;
                    this.SendPropertyChanged("Kilshowdoc");
                }
            }
        }

        public int? Numdescargue
        {
            get
            {
                return this._Numdescargue;
            }
            set
            {
                if (this._Numdescargue != value)
                {
                    this.SendPropertyChanging("Numdescargue");
                    this._Numdescargue = value;
                    this.SendPropertyChanged("Numdescargue");
                }
            }
        }

        public string? Codagencia
        {
            get
            {
                return this._Codagencia;
            }
            set
            {
                if (this._Codagencia != value)
                {
                    this.SendPropertyChanging("Codagencia");
                    this._Codagencia = value;
                    this.SendPropertyChanged("Codagencia");
                }
            }
        }

        public DateTime? Fecha
        {
            get
            {
                return this._Fecha;
            }
            set
            {
                if (this._Fecha != value)
                {
                    this.SendPropertyChanging("Fecha");
                    this._Fecha = value;
                    this.SendPropertyChanged("Fecha");
                }
            }
        }

        public int? Lectura
        {
            get
            {
                return this._Lectura;
            }
            set
            {
                if (this._Lectura != value)
                {
                    this.SendPropertyChanging("Lectura");
                    this._Lectura = value;
                    this.SendPropertyChanged("Lectura");
                }
            }
        }

        public virtual Compra Compra
        {
            get
            {
                return this._Compra;
            }
            set
            {
                if (this._Compra != value)
                {
                    this.SendPropertyChanging("Compra");
                    this._Compra = value;
                    this.SendPropertyChanged("Compra");
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
