//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 11/10/2024 2:18:02 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Configuration;

namespace SistemaOro.Data.Entities
{

    public partial class DataContext : DbContext
    {

        public DataContext() :
            base()
        {
            OnCreated();
        }

        public DataContext(DbContextOptions<DataContext> options) :
            base(options)
        {
            OnCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured ||
                (!optionsBuilder.Options.Extensions.OfType<RelationalOptionsExtension>().Any(ext => !string.IsNullOrEmpty(ext.ConnectionString) || ext.Connection != null) &&
                 !optionsBuilder.Options.Extensions.Any(ext => !(ext is RelationalOptionsExtension) && !(ext is CoreOptionsExtension))))
            {
                optionsBuilder.UseSqlServer(GetConnectionString("ConnectionString"));
            }
            CustomizeConfiguration(ref optionsBuilder);
            base.OnConfiguring(optionsBuilder);
        }

        private static string GetConnectionString(string connectionStringName)
        {
            var configurationBuilder = new ConfigurationBuilder().AddJsonFile("appsettings.json", optional: true, reloadOnChange: false);
            var configuration = configurationBuilder.Build();
            return configuration.GetConnectionString(connectionStringName);
        }

        partial void CustomizeConfiguration(ref DbContextOptionsBuilder optionsBuilder);

        public virtual DbSet<Adelanto> Adelantos
        {
            get;
            set;
        }

        public virtual DbSet<Agencia> Agencias
        {
            get;
            set;
        }

        public virtual DbSet<Caja> Cajas
        {
            get;
            set;
        }

        public virtual DbSet<CierrePrecio> CierrePrecios
        {
            get;
            set;
        }

        public virtual DbSet<Cliente> Clientes
        {
            get;
            set;
        }

        public virtual DbSet<Compra> Compras
        {
            get;
            set;
        }

        public virtual DbSet<ComprasAdelanto> ComprasAdelantos
        {
            get;
            set;
        }

        public virtual DbSet<Descargue> Descargues
        {
            get;
            set;
        }

        public virtual DbSet<DetCompra> DetCompras
        {
            get;
            set;
        }

        public virtual DbSet<Detacaja> Detacajas
        {
            get;
            set;
        }

        public virtual DbSet<Detacierre> Detacierres
        {
            get;
            set;
        }

        public virtual DbSet<Estado> Estados
        {
            get;
            set;
        }

        public virtual DbSet<FormaPago> FormaPagos
        {
            get;
            set;
        }

        public virtual DbSet<Id> Id
        {
            get;
            set;
        }

        public virtual DbSet<Liquidacion2015> Liquidacion2015s
        {
            get;
            set;
        }

        public virtual DbSet<Listado> Listados
        {
            get;
            set;
        }

        public virtual DbSet<Mcaja> Mcajas
        {
            get;
            set;
        }

        public virtual DbSet<Moneda> Monedas
        {
            get;
            set;
        }

        public virtual DbSet<Movcaja> Movcajas
        {
            get;
            set;
        }

        public virtual DbSet<PagosAdelantado> PagosAdelantados
        {
            get;
            set;
        }

        public virtual DbSet<Pica> Picas
        {
            get;
            set;
        }

        public virtual DbSet<PrecioKilate> PrecioKilates
        {
            get;
            set;
        }

        public virtual DbSet<Precio> Precios
        {
            get;
            set;
        }

        public virtual DbSet<ReporteCaja> ReporteCajas
        {
            get;
            set;
        }

        public virtual DbSet<Rubro> Rubros
        {
            get;
            set;
        }

        public virtual DbSet<RubrosCaja> RubrosCajas
        {
            get;
            set;
        }

        public virtual DbSet<TipoCambio> TipoCambios
        {
            get;
            set;
        }

        public virtual DbSet<TipoPreciosPagado> TipoPreciosPagados
        {
            get;
            set;
        }

        public virtual DbSet<Tmpprecio> Tmpprecios
        {
            get;
            set;
        }

        public virtual DbSet<Usuario> Usuarios
        {
            get;
            set;
        }

        public virtual DbSet<ComprasOperador> ComprasOperadors
        {
            get;
            set;
        }

        public virtual DbSet<MovimientosCajaSelect> MovimientosCajaSelects
        {
            get;
            set;
        }

        public virtual DbSet<TransaccionEfectivo> TransaccionEfectivos
        {
            get;
            set;
        }

        public virtual DbSet<TipoDocumento> TipoDocumentos
        {
            get;
            set;
        }

        public virtual DbSet<TipoPrecio> TipoPrecios
        {
            get;
            set;
        }

        public virtual DbSet<ComprasOperador1> ComprasOperador1s
        {
            get;
            set;
        }

        public virtual DbSet<DescargueByCompra> DescargueByCompras
        {
            get;
            set;
        }

        public virtual DbSet<VVariacionesCliente> VVariacionesClientes
        {
            get;
            set;
        }

        public virtual DbSet<DetalleCompra> DetalleCompras
        {
            get;
            set;
        }

        #region Methods

        public void AnularCompra (string numeroCompra, string agencia)
        {

            DbConnection connection = this.Database.GetDbConnection();
            bool needClose = false;
            if (connection.State != ConnectionState.Open)
            {
                connection.Open();
                needClose = true;
            }

            try
            {
                using (DbCommand cmd = connection.CreateCommand())
                {
                    if (this.Database.GetCommandTimeout().HasValue)
                        cmd.CommandTimeout = this.Database.GetCommandTimeout().Value;
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.CommandText = @"dbo.anularCompra";

                    DbParameter numeroCompraParameter = cmd.CreateParameter();
                    numeroCompraParameter.ParameterName = "numeroCompra";
                    numeroCompraParameter.Direction = ParameterDirection.Input;
                    numeroCompraParameter.DbType = DbType.String;
                    numeroCompraParameter.Size = 20;
                    if (numeroCompra != null)
                    {
                        numeroCompraParameter.Value = numeroCompra;
                    }
                    else
                    {
                        numeroCompraParameter.Value = DBNull.Value;
                    }
                    cmd.Parameters.Add(numeroCompraParameter);

                    DbParameter agenciaParameter = cmd.CreateParameter();
                    agenciaParameter.ParameterName = "agencia";
                    agenciaParameter.Direction = ParameterDirection.Input;
                    agenciaParameter.DbType = DbType.String;
                    agenciaParameter.Size = 20;
                    if (agencia != null)
                    {
                        agenciaParameter.Value = agencia;
                    }
                    else
                    {
                        agenciaParameter.Value = DBNull.Value;
                    }
                    cmd.Parameters.Add(agenciaParameter);
                    cmd.ExecuteNonQuery();
                }
            }
            finally
            {
                if (needClose)
                    connection.Close();
            }
        }

        public async Task AnularCompraAsync (string numeroCompra, string agencia)
        {

            DbConnection connection = this.Database.GetDbConnection();
            bool needClose = false;
            if (connection.State != ConnectionState.Open)
            {
                await connection.OpenAsync();
                needClose = true;
            }

            try
            {
                using (DbCommand cmd = connection.CreateCommand())
                {
                    if (this.Database.GetCommandTimeout().HasValue)
                        cmd.CommandTimeout = this.Database.GetCommandTimeout().Value;
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.CommandText = @"dbo.anularCompra";

                    DbParameter numeroCompraParameter = cmd.CreateParameter();
                    numeroCompraParameter.ParameterName = "numeroCompra";
                    numeroCompraParameter.Direction = ParameterDirection.Input;
                    numeroCompraParameter.DbType = DbType.String;
                    numeroCompraParameter.Size = 20;
                    if (numeroCompra != null)
                    {
                        numeroCompraParameter.Value = numeroCompra;
                    }
                    else
                    {
                        numeroCompraParameter.Value = DBNull.Value;
                    }
                    cmd.Parameters.Add(numeroCompraParameter);

                    DbParameter agenciaParameter = cmd.CreateParameter();
                    agenciaParameter.ParameterName = "agencia";
                    agenciaParameter.Direction = ParameterDirection.Input;
                    agenciaParameter.DbType = DbType.String;
                    agenciaParameter.Size = 20;
                    if (agencia != null)
                    {
                        agenciaParameter.Value = agencia;
                    }
                    else
                    {
                        agenciaParameter.Value = DBNull.Value;
                    }
                    cmd.Parameters.Add(agenciaParameter);
                    await cmd.ExecuteNonQueryAsync();
                }
            }
            finally
            {
                if (needClose)
                    connection.Close();
            }
        }

        #endregion

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            this.AdelantoMapping(modelBuilder);
            this.CustomizeAdelantoMapping(modelBuilder);

            this.AgenciaMapping(modelBuilder);
            this.CustomizeAgenciaMapping(modelBuilder);

            this.CajaMapping(modelBuilder);
            this.CustomizeCajaMapping(modelBuilder);

            this.CierrePrecioMapping(modelBuilder);
            this.CustomizeCierrePrecioMapping(modelBuilder);

            this.ClienteMapping(modelBuilder);
            this.CustomizeClienteMapping(modelBuilder);

            this.CompraMapping(modelBuilder);
            this.CustomizeCompraMapping(modelBuilder);

            this.ComprasAdelantoMapping(modelBuilder);
            this.CustomizeComprasAdelantoMapping(modelBuilder);

            this.DescargueMapping(modelBuilder);
            this.CustomizeDescargueMapping(modelBuilder);

            this.DetCompraMapping(modelBuilder);
            this.CustomizeDetCompraMapping(modelBuilder);

            this.DetacajaMapping(modelBuilder);
            this.CustomizeDetacajaMapping(modelBuilder);

            this.DetacierreMapping(modelBuilder);
            this.CustomizeDetacierreMapping(modelBuilder);

            this.EstadoMapping(modelBuilder);
            this.CustomizeEstadoMapping(modelBuilder);

            this.FormaPagoMapping(modelBuilder);
            this.CustomizeFormaPagoMapping(modelBuilder);

            this.IdMapping(modelBuilder);
            this.CustomizeIdMapping(modelBuilder);

            this.Liquidacion2015Mapping(modelBuilder);
            this.CustomizeLiquidacion2015Mapping(modelBuilder);

            this.ListadoMapping(modelBuilder);
            this.CustomizeListadoMapping(modelBuilder);

            this.McajaMapping(modelBuilder);
            this.CustomizeMcajaMapping(modelBuilder);

            this.MonedaMapping(modelBuilder);
            this.CustomizeMonedaMapping(modelBuilder);

            this.MovcajaMapping(modelBuilder);
            this.CustomizeMovcajaMapping(modelBuilder);

            this.PagosAdelantadoMapping(modelBuilder);
            this.CustomizePagosAdelantadoMapping(modelBuilder);

            this.PicaMapping(modelBuilder);
            this.CustomizePicaMapping(modelBuilder);

            this.PrecioKilateMapping(modelBuilder);
            this.CustomizePrecioKilateMapping(modelBuilder);

            this.PrecioMapping(modelBuilder);
            this.CustomizePrecioMapping(modelBuilder);

            this.ReporteCajaMapping(modelBuilder);
            this.CustomizeReporteCajaMapping(modelBuilder);

            this.RubroMapping(modelBuilder);
            this.CustomizeRubroMapping(modelBuilder);

            this.RubrosCajaMapping(modelBuilder);
            this.CustomizeRubrosCajaMapping(modelBuilder);

            this.TipoCambioMapping(modelBuilder);
            this.CustomizeTipoCambioMapping(modelBuilder);

            this.TipoPreciosPagadoMapping(modelBuilder);
            this.CustomizeTipoPreciosPagadoMapping(modelBuilder);

            this.TmpprecioMapping(modelBuilder);
            this.CustomizeTmpprecioMapping(modelBuilder);

            this.UsuarioMapping(modelBuilder);
            this.CustomizeUsuarioMapping(modelBuilder);

            this.ComprasOperadorMapping(modelBuilder);
            this.CustomizeComprasOperadorMapping(modelBuilder);

            this.MovimientosCajaSelectMapping(modelBuilder);
            this.CustomizeMovimientosCajaSelectMapping(modelBuilder);

            this.TransaccionEfectivoMapping(modelBuilder);
            this.CustomizeTransaccionEfectivoMapping(modelBuilder);

            this.TipoDocumentoMapping(modelBuilder);
            this.CustomizeTipoDocumentoMapping(modelBuilder);

            this.TipoPrecioMapping(modelBuilder);
            this.CustomizeTipoPrecioMapping(modelBuilder);

            this.ComprasOperador1Mapping(modelBuilder);
            this.CustomizeComprasOperador1Mapping(modelBuilder);

            this.DescargueByCompraMapping(modelBuilder);
            this.CustomizeDescargueByCompraMapping(modelBuilder);

            this.VVariacionesClienteMapping(modelBuilder);
            this.CustomizeVVariacionesClienteMapping(modelBuilder);

            this.DetalleCompraMapping(modelBuilder);
            this.CustomizeDetalleCompraMapping(modelBuilder);

            RelationshipsMapping(modelBuilder);
            CustomizeMapping(ref modelBuilder);
        }

        #region Adelanto Mapping

        private void AdelantoMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Adelanto>().ToTable(@"Adelanto");
            modelBuilder.Entity<Adelanto>().Property(x => x.Idsalida).HasColumnName(@"Idsalida").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<Adelanto>().Property(x => x.Codcliente).HasColumnName(@"Codcliente").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<Adelanto>().Property(x => x.Numcompra).HasColumnName(@"Numcompra").HasColumnType(@"nvarchar(20)").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<Adelanto>().Property(x => x.Fecha).HasColumnName(@"Fecha").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Adelanto>().Property(x => x.Monto).HasColumnName(@"Monto").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Adelanto>().Property(x => x.Saldo).HasColumnName(@"Saldo").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Adelanto>().Property(x => x.Efectivo).HasColumnName(@"Efectivo").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Adelanto>().Property(x => x.Cheque).HasColumnName(@"Cheque").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Adelanto>().Property(x => x.Transferencia).HasColumnName(@"Transferencia").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Adelanto>().Property(x => x.Codcaja).HasColumnName(@"Codcaja").ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<Adelanto>().Property(x => x.Usuario).HasColumnName(@"Usuario").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Adelanto>().Property(x => x.MontoLetras).HasColumnName(@"MontoLetras").ValueGeneratedNever();
            modelBuilder.Entity<Adelanto>().Property(x => x.Hora).HasColumnName(@"Hora").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Adelanto>().Property(x => x.Codmoneda).HasColumnName(@"Codmoneda").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Adelanto>().Property(x => x.Estado).HasColumnName(@"Estado").IsRequired().ValueGeneratedNever().HasPrecision(3, 0).HasDefaultValueSql(@"1");
            modelBuilder.Entity<Adelanto>().HasKey(@"Idsalida");
        }

        partial void CustomizeAdelantoMapping(ModelBuilder modelBuilder);

        #endregion

        #region Agencia Mapping

        private void AgenciaMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Agencia>().ToTable(@"Agencia");
            modelBuilder.Entity<Agencia>().Property(x => x.Codagencia).HasColumnName(@"Codagencia").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<Agencia>().Property(x => x.Nomagencia).HasColumnName(@"Nomagencia").IsRequired().ValueGeneratedNever().HasMaxLength(150);
            modelBuilder.Entity<Agencia>().Property(x => x.Diragencia).HasColumnName(@"Diragencia").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Agencia>().Property(x => x.Disagencia).HasColumnName(@"Disagencia").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<Agencia>().Property(x => x.Telagencia).HasColumnName(@"Telagencia").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<Agencia>().Property(x => x.Numcompra).HasColumnName(@"Numcompra").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Agencia>().Property(x => x.Logo).HasColumnName(@"Logo").ValueGeneratedNever();
            modelBuilder.Entity<Agencia>().Property(x => x.Ruc).HasColumnName(@"Ruc").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Agencia>().HasKey(@"Codagencia");
        }

        partial void CustomizeAgenciaMapping(ModelBuilder modelBuilder);

        #endregion

        #region Caja Mapping

        private void CajaMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Caja>().ToTable(@"Caja");
            modelBuilder.Entity<Caja>().Property(x => x.Codcaja).HasColumnName(@"Codcaja").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<Caja>().Property(x => x.Descripcion).HasColumnName(@"Descripcion").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Caja>().Property(x => x.Codagencia).HasColumnName(@"Codagencia").ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<Caja>().HasKey(@"Codcaja");
        }

        partial void CustomizeCajaMapping(ModelBuilder modelBuilder);

        #endregion

        #region CierrePrecio Mapping

        private void CierrePrecioMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CierrePrecio>().ToTable(@"CierrePrecio");
            modelBuilder.Entity<CierrePrecio>().Property(x => x.Codcierre).HasColumnName(@"Codcierre").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<CierrePrecio>().Property(x => x.Codcliente).HasColumnName(@"Codcliente").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<CierrePrecio>().Property(x => x.Status).HasColumnName(@"Status").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<CierrePrecio>().Property(x => x.OnzasFinas).HasColumnName(@"OnzasFinas").HasColumnType(@"decimal(12,3)").IsRequired().ValueGeneratedNever().HasPrecision(12, 3);
            modelBuilder.Entity<CierrePrecio>().Property(x => x.GramosFinos).HasColumnName(@"GramosFinos").HasColumnType(@"decimal(12,2)").IsRequired().ValueGeneratedNever().HasPrecision(12, 2);
            modelBuilder.Entity<CierrePrecio>().Property(x => x.PrecioOro).HasColumnName(@"PrecioOro").HasColumnType(@"decimal(12,2)").IsRequired().ValueGeneratedNever().HasPrecision(12, 2);
            modelBuilder.Entity<CierrePrecio>().Property(x => x.PrecioBase).HasColumnName(@"PrecioBase").HasColumnType(@"decimal(12,2)").IsRequired().ValueGeneratedNever().HasPrecision(12, 2);
            modelBuilder.Entity<CierrePrecio>().Property(x => x.SaldoOnzas).HasColumnName(@"SaldoOnzas").HasColumnType(@"decimal(12,3)").IsRequired().ValueGeneratedNever().HasPrecision(12, 3);
            modelBuilder.Entity<CierrePrecio>().Property(x => x.Fecha).HasColumnName(@"Fecha").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<CierrePrecio>().Property(x => x.Margen).HasColumnName(@"Margen").HasColumnType(@"decimal(12,2)").IsRequired().ValueGeneratedNever().HasPrecision(12, 2);
            modelBuilder.Entity<CierrePrecio>().HasKey(@"Codcierre");
        }

        partial void CustomizeCierrePrecioMapping(ModelBuilder modelBuilder);

        #endregion

        #region Cliente Mapping

        private void ClienteMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Cliente>().ToTable(@"Cliente");
            modelBuilder.Entity<Cliente>().Property(x => x.Codcliente).HasColumnName(@"Codcliente").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<Cliente>().Property(x => x.Nombres).HasColumnName(@"Nombres").IsRequired().ValueGeneratedNever().HasMaxLength(35);
            modelBuilder.Entity<Cliente>().Property(x => x.Apellidos).HasColumnName(@"Apellidos").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Cliente>().Property(x => x.Numcedula).HasColumnName(@"Numcedula").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Cliente>().Property(x => x.FEmision).HasColumnName(@"FEmision").ValueGeneratedNever();
            modelBuilder.Entity<Cliente>().Property(x => x.FVencimiento).HasColumnName(@"FVencimiento").ValueGeneratedNever();
            modelBuilder.Entity<Cliente>().Property(x => x.Direccion).HasColumnName(@"Direccion").IsRequired().ValueGeneratedNever().HasMaxLength(2147483647);
            modelBuilder.Entity<Cliente>().Property(x => x.FNacimiento).HasColumnName(@"FNacimiento").ValueGeneratedNever();
            modelBuilder.Entity<Cliente>().Property(x => x.Estadocivil).HasColumnName(@"Estadocivil").ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<Cliente>().Property(x => x.Ciudad).HasColumnName(@"Ciudad").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Cliente>().Property(x => x.Telefono).HasColumnName(@"Telefono").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Cliente>().Property(x => x.Celular).HasColumnName(@"Celular").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Cliente>().Property(x => x.Email).HasColumnName(@"Email").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Cliente>().Property(x => x.FIngreso).HasColumnName(@"FIngreso").ValueGeneratedNever();
            modelBuilder.Entity<Cliente>().Property(x => x.Ocupacion).HasColumnName(@"Ocupacion").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Cliente>().Property(x => x.DireccionNegocio).HasColumnName(@"DireccionNegocio").ValueGeneratedNever().HasMaxLength(2147483647);
            modelBuilder.Entity<Cliente>().Property(x => x.TiempoNeg).HasColumnName(@"TiempoNeg").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Cliente>().Property(x => x.OtraAe).HasColumnName(@"OtraAe").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Cliente>().Property(x => x.DescOtra).HasColumnName(@"DescOtra").ValueGeneratedNever().HasMaxLength(2147483647);
            modelBuilder.Entity<Cliente>().Property(x => x.NomCuenta).HasColumnName(@"NomCuenta").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Cliente>().Property(x => x.NumCuenta).HasColumnName(@"NumCuenta").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Cliente>().Property(x => x.NomBanco).HasColumnName(@"NomBanco").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Cliente>().Property(x => x.MontoMensual).HasColumnName(@"MontoMensual").HasColumnType(@"decimal(19,4)").ValueGeneratedNever().HasPrecision(19, 4);
            modelBuilder.Entity<Cliente>().Property(x => x.TotalOperaciones).HasColumnName(@"TotalOperaciones").HasColumnType(@"decimal(12,3)").ValueGeneratedNever().HasPrecision(12, 3);
            modelBuilder.Entity<Cliente>().Property(x => x.ActuaPor).HasColumnName(@"ActuaPor").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Cliente>().Property(x => x.NombreTercero).HasColumnName(@"NombreTercero").ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<Cliente>().Property(x => x.DireccionTercero).HasColumnName(@"DireccionTercero").ValueGeneratedNever().HasMaxLength(2147483647);
            modelBuilder.Entity<Cliente>().Property(x => x.Pica).HasColumnName(@"Pica").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Cliente>().Property(x => x.Ocupacion2).HasColumnName(@"Ocupacion2").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50).HasDefaultValueSql(@"'Cliente Generico'");
            modelBuilder.Entity<Cliente>().Property(x => x.Idtipodocumento).HasColumnName(@"Idtipodocumento").ValueGeneratedNever().HasPrecision(10, 0).HasDefaultValueSql(@"0");
            modelBuilder.Entity<Cliente>().HasKey(@"Codcliente");
        }

        partial void CustomizeClienteMapping(ModelBuilder modelBuilder);

        #endregion

        #region Compra Mapping

        private void CompraMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Compra>().ToTable(@"Compra");
            modelBuilder.Entity<Compra>().Property(x => x.Numcompra).HasColumnName(@"Numcompra").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<Compra>().Property(x => x.Codagencia).HasColumnName(@"Codagencia").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<Compra>().Property(x => x.Codcliente).HasColumnName(@"Codcliente").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<Compra>().Property(x => x.Codcaja).HasColumnName(@"Codcaja").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<Compra>().Property(x => x.Peso).HasColumnName(@"Peso").HasColumnType(@"decimal(11,2)").IsRequired().ValueGeneratedNever().HasPrecision(11, 2);
            modelBuilder.Entity<Compra>().Property(x => x.Codmoneda).HasColumnName(@"Codmoneda").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Compra>().Property(x => x.Total).HasColumnName(@"Total").HasColumnType(@"decimal(15,2)").IsRequired().ValueGeneratedNever().HasPrecision(15, 2);
            modelBuilder.Entity<Compra>().Property(x => x.Fecha).HasColumnName(@"Fecha").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Compra>().Property(x => x.Codestado).HasColumnName(@"Codestado").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Compra>().Property(x => x.Usuario).HasColumnName(@"Usuario").HasColumnType(@"nvarchar(20)").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<Compra>().Property(x => x.Hora).HasColumnName(@"Hora").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Compra>().Property(x => x.FormaPago).HasColumnName(@"FormaPago").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Compra>().Property(x => x.Dgnumdes).HasColumnName(@"Dgnumdes").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0).HasDefaultValueSql(@"0");
            modelBuilder.Entity<Compra>().Property(x => x.Efectivo).HasColumnName(@"Efectivo").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Compra>().Property(x => x.Cheque).HasColumnName(@"Cheque").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Compra>().Property(x => x.Transferencia).HasColumnName(@"Transferencia").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Compra>().Property(x => x.PorCobrar).HasColumnName(@"PorCobrar").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Compra>().Property(x => x.PorPagar).HasColumnName(@"PorPagar").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Compra>().Property(x => x.Adelantos).HasColumnName(@"Adelantos").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Compra>().Property(x => x.SaldoPorPagar).HasColumnName(@"SaldoPorPagar").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Compra>().Property(x => x.SaldoAdelanto).HasColumnName(@"SaldoAdelanto").HasColumnType(@"decimal(12,3)").ValueGeneratedNever().HasPrecision(12, 3).HasDefaultValueSql(@"0");
            modelBuilder.Entity<Compra>().Property(x => x.SaldoAdelantoDolares).HasColumnName(@"SaldoAdelantoDolares").HasColumnType(@"decimal(12,3)").ValueGeneratedNever().HasPrecision(12, 3);
            modelBuilder.Entity<Compra>().Property(x => x.Nocontrato).HasColumnName(@"Nocontrato").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Compra>().Property(x => x.Subtotal).HasColumnName(@"Subtotal").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Compra>().Property(x => x.Descuento).HasColumnName(@"Descuento").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Compra>().HasKey(@"Numcompra");
        }

        partial void CustomizeCompraMapping(ModelBuilder modelBuilder);

        #endregion

        #region ComprasAdelanto Mapping

        private void ComprasAdelantoMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ComprasAdelanto>().ToTable(@"ComprasAdelanto");
            modelBuilder.Entity<ComprasAdelanto>().Property(x => x.IdcomprasAdelantos).HasColumnName(@"IdcomprasAdelantos").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<ComprasAdelanto>().Property(x => x.Numcompra).HasColumnName(@"Numcompra").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<ComprasAdelanto>().Property(x => x.Idadelanto).HasColumnName(@"Idadelanto").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<ComprasAdelanto>().Property(x => x.Codcliente).HasColumnName(@"Codcliente").ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<ComprasAdelanto>().Property(x => x.Sinicial).HasColumnName(@"Sinicial").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<ComprasAdelanto>().Property(x => x.Monto).HasColumnName(@"Monto").HasColumnType(@"decimal(18,3)").IsRequired().ValueGeneratedNever().HasPrecision(18, 3);
            modelBuilder.Entity<ComprasAdelanto>().Property(x => x.Sfinal).HasColumnName(@"Sfinal").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<ComprasAdelanto>().Property(x => x.Fecha).HasColumnName(@"Fecha").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<ComprasAdelanto>().Property(x => x.Codcaja).HasColumnName(@"Codcaja").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<ComprasAdelanto>().Property(x => x.Usuario).HasColumnName(@"Usuario").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<ComprasAdelanto>().Property(x => x.Hora).HasColumnName(@"Hora").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<ComprasAdelanto>().Property(x => x.Codagencia).HasColumnName(@"Codagencia").ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<ComprasAdelanto>().Property(x => x.Codmoneda).HasColumnName(@"Codmoneda").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<ComprasAdelanto>().HasKey(@"IdcomprasAdelantos");
        }

        partial void CustomizeComprasAdelantoMapping(ModelBuilder modelBuilder);

        #endregion

        #region Descargue Mapping

        private void DescargueMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Descargue>().ToTable(@"Descargue");
            modelBuilder.Entity<Descargue>().Property(x => x.Dgnumdes).HasColumnName(@"Dgnumdes").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Descargue>().Property(x => x.Dgcodage).HasColumnName(@"Dgcodage").IsRequired().ValueGeneratedNever().HasMaxLength(4);
            modelBuilder.Entity<Descargue>().Property(x => x.Dgcodcaj).HasColumnName(@"Dgcodcaj").IsRequired().ValueGeneratedNever().HasMaxLength(7);
            modelBuilder.Entity<Descargue>().Property(x => x.Dgusuari).HasColumnName(@"Dgusuari").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<Descargue>().Property(x => x.Dgcancom).HasColumnName(@"Dgcancom").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Descargue>().Property(x => x.Dgpesbrt).HasColumnName(@"Dgpesbrt").HasColumnType(@"decimal(11,2)").IsRequired().ValueGeneratedNever().HasPrecision(11, 2);
            modelBuilder.Entity<Descargue>().Property(x => x.Dgpesntt).HasColumnName(@"Dgpesntt").HasColumnType(@"decimal(11,2)").IsRequired().ValueGeneratedNever().HasPrecision(11, 2);
            modelBuilder.Entity<Descargue>().Property(x => x.Dgimptcom).HasColumnName(@"Dgimptcom").HasColumnType(@"decimal(11,2)").IsRequired().ValueGeneratedNever().HasPrecision(11, 2);
            modelBuilder.Entity<Descargue>().Property(x => x.Dgfecdes).HasColumnName(@"Dgfecdes").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Descargue>().Property(x => x.Dgfecgen).HasColumnName(@"Dgfecgen").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Descargue>().HasKey(@"Dgnumdes");
        }

        partial void CustomizeDescargueMapping(ModelBuilder modelBuilder);

        #endregion

        #region DetCompra Mapping

        private void DetCompraMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DetCompra>().ToTable(@"DetCompra");
            modelBuilder.Entity<DetCompra>().Property(x => x.Idetacompra).HasColumnName(@"idetacompra").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<DetCompra>().Property(x => x.Numcompra).HasColumnName(@"Numcompra").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<DetCompra>().Property(x => x.Linea).HasColumnName(@"Linea").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<DetCompra>().Property(x => x.Descripcion).HasColumnName(@"Descripcion").IsRequired().ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<DetCompra>().Property(x => x.Kilate).HasColumnName(@"Kilate").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<DetCompra>().Property(x => x.Preciok).HasColumnName(@"Preciok").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<DetCompra>().Property(x => x.Peso).HasColumnName(@"Peso").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<DetCompra>().Property(x => x.Importe).HasColumnName(@"Importe").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<DetCompra>().Property(x => x.Kilshowdoc).HasColumnName(@"Kilshowdoc").ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<DetCompra>().Property(x => x.Numdescargue).HasColumnName(@"Numdescargue").ValueGeneratedNever().HasPrecision(10, 0).HasDefaultValueSql(@"0");
            modelBuilder.Entity<DetCompra>().Property(x => x.Codagencia).HasColumnName(@"Codagencia").ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<DetCompra>().Property(x => x.Fecha).HasColumnName(@"Fecha").ValueGeneratedNever();
            modelBuilder.Entity<DetCompra>().HasKey(@"Idetacompra");
        }

        partial void CustomizeDetCompraMapping(ModelBuilder modelBuilder);

        #endregion

        #region Detacaja Mapping

        private void DetacajaMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Detacaja>().ToTable(@"Detacaja");
            modelBuilder.Entity<Detacaja>().Property(x => x.IdDetaCaja).HasColumnName(@"IdDetaCaja").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<Detacaja>().Property(x => x.Fecha).HasColumnName(@"Fecha").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Detacaja>().Property(x => x.Idcaja).HasColumnName(@"Idcaja").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Detacaja>().Property(x => x.Idmov).HasColumnName(@"Idmov").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Detacaja>().Property(x => x.Hora).HasColumnName(@"Hora").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Detacaja>().Property(x => x.Concepto).HasColumnName(@"Concepto").ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<Detacaja>().Property(x => x.Efectivo).HasColumnName(@"Efectivo").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Detacaja>().Property(x => x.Referencia).HasColumnName(@"Referencia").ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<Detacaja>().Property(x => x.Cheque).HasColumnName(@"Cheque").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Detacaja>().Property(x => x.Transferencia).HasColumnName(@"Transferencia").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Detacaja>().Property(x => x.Codcaja).HasColumnName(@"Codcaja").ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<Detacaja>().Property(x => x.Tipocambio).HasColumnName(@"Tipocambio").HasColumnType(@"decimal(12,4)").ValueGeneratedNever().HasPrecision(12, 4).HasDefaultValueSql(@"1");
            modelBuilder.Entity<Detacaja>().HasKey(@"IdDetaCaja");
        }

        partial void CustomizeDetacajaMapping(ModelBuilder modelBuilder);

        #endregion

        #region Detacierre Mapping

        private void DetacierreMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Detacierre>().ToTable(@"Detacierre");
            modelBuilder.Entity<Detacierre>().Property(x => x.Codcierre).HasColumnName(@"Codcierre").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Detacierre>().Property(x => x.Numcompra).HasColumnName(@"Numcompra").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<Detacierre>().Property(x => x.Onzas).HasColumnName(@"Onzas").HasColumnType(@"decimal(12,3)").IsRequired().ValueGeneratedNever().HasPrecision(12, 3);
            modelBuilder.Entity<Detacierre>().Property(x => x.Saldo).HasColumnName(@"Saldo").HasColumnType(@"decimal(12,3)").IsRequired().ValueGeneratedNever().HasPrecision(12, 3);
            modelBuilder.Entity<Detacierre>().Property(x => x.Fecha).HasColumnName(@"Fecha").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Detacierre>().Property(x => x.Cantidad).HasColumnName(@"Cantidad").HasColumnType(@"decimal(12,3)").IsRequired().ValueGeneratedNever().HasPrecision(12, 3);
            modelBuilder.Entity<Detacierre>().Property(x => x.Codagencia).HasColumnName(@"Codagencia").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<Detacierre>().HasKey(@"Codcierre", @"Numcompra");
        }

        partial void CustomizeDetacierreMapping(ModelBuilder modelBuilder);

        #endregion

        #region Estado Mapping

        private void EstadoMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Estado>().ToTable(@"Estado");
            modelBuilder.Entity<Estado>().Property(x => x.Codestado).HasColumnName(@"Codestado").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Estado>().Property(x => x.DescEstado).HasColumnName(@"DescEstado").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Estado>().HasKey(@"Codestado");
        }

        partial void CustomizeEstadoMapping(ModelBuilder modelBuilder);

        #endregion

        #region FormaPago Mapping

        private void FormaPagoMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<FormaPago>().ToTable(@"FormaPago");
            modelBuilder.Entity<FormaPago>().Property(x => x.Idmov).HasColumnName(@"Idmov").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<FormaPago>().Property(x => x.Descripcion).HasColumnName(@"Descripcion").HasColumnType(@"decimal(12,2)").ValueGeneratedNever().HasPrecision(12, 2);
            modelBuilder.Entity<FormaPago>().Property(x => x.Naturaleza).HasColumnName(@"Naturaleza").HasColumnType(@"decimal(12,2)").ValueGeneratedNever().HasPrecision(12, 2);
            modelBuilder.Entity<FormaPago>().HasKey(@"Idmov");
        }

        partial void CustomizeFormaPagoMapping(ModelBuilder modelBuilder);

        #endregion

        #region Id Mapping

        private void IdMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Id>().ToTable(@"Id");
            modelBuilder.Entity<Id>().Property(x => x.Codcliente).HasColumnName(@"Codcliente").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Id>().Property(x => x.Codagencia).HasColumnName(@"Codagencia").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Id>().Property(x => x.Numcompra).HasColumnName(@"Numcompra").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Id>().Property(x => x.Idadelanto).HasColumnName(@"Idadelanto").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Id>().Property(x => x.Idcompras).HasColumnName(@"Idcompras").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Id>().Property(x => x.IdAdelantos).HasColumnName(@"IdAdelantos").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Id>().Property(x => x.SaldoAnterior).HasColumnName(@"SaldoAnterior").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Id>().Property(x => x.CierreCompra).HasColumnName(@"CierreCompra").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Id>().Property(x => x.PrestamoEgreso).HasColumnName(@"PrestamoEgreso").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Id>().Property(x => x.PrestamoIngreso).HasColumnName(@"PrestamoIngreso").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Id>().Property(x => x.AnularCompra).HasColumnName(@"AnularCompra").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Id>().Property(x => x.AnularAdelanto).HasColumnName(@"AnularAdelanto").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Id>().Property(x => x.VariasCompras).HasColumnName(@"VariasCompras").ValueGeneratedNever();
            modelBuilder.Entity<Id>().Property(x => x.Recibe).HasColumnName(@"Recibe").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Id>().Property(x => x.PagoAdelanto).HasColumnName(@"PagoAdelanto").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Id>().Property(x => x.Idreserva).HasColumnName(@"Idreserva").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Id>().Property(x => x.Backup).HasColumnName(@"Backup").ValueGeneratedNever();
            modelBuilder.Entity<Id>().Property(x => x.Cordobas).HasColumnName(@"Cordobas").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Id>().Property(x => x.Dolares).HasColumnName(@"Dolares").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Id>().Property(x => x.Nocontrato).HasColumnName(@"Nocontrato").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Id>().Property(x => x.Logo).HasColumnName(@"Logo").ValueGeneratedNever();
            modelBuilder.Entity<Id>().HasKey(@"Codcliente");
        }

        partial void CustomizeIdMapping(ModelBuilder modelBuilder);

        #endregion

        #region Liquidacion2015 Mapping

        private void Liquidacion2015Mapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Liquidacion2015>().ToTable(@"Liquidacion2015");
            modelBuilder.Entity<Liquidacion2015>().Property(x => x.Numcompra).HasColumnName(@"Numcompra").IsRequired().ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Liquidacion2015>().Property(x => x.Codcliente).HasColumnName(@"Codcliente").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Liquidacion2015>().Property(x => x.Codcaja).HasColumnName(@"Codcaja").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Liquidacion2015>().Property(x => x.Peso).HasColumnName(@"Peso").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Liquidacion2015>().Property(x => x.Total).HasColumnName(@"Total").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Liquidacion2015>().Property(x => x.Fecha).HasColumnName(@"Fecha").ValueGeneratedNever();
            modelBuilder.Entity<Liquidacion2015>().Property(x => x.Usuario).HasColumnName(@"Usuario").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Liquidacion2015>().Property(x => x.Hora).HasColumnName(@"Hora").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Liquidacion2015>().Property(x => x.Cliente).HasColumnName(@"Cliente").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Liquidacion2015>().HasKey(@"Numcompra");
        }

        partial void CustomizeLiquidacion2015Mapping(ModelBuilder modelBuilder);

        #endregion

        #region Listado Mapping

        private void ListadoMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Listado>().HasNoKey();
            modelBuilder.Entity<Listado>().ToView(@"Listado");
            modelBuilder.Entity<Listado>().Property(x => x.Solicitud).HasColumnName(@"Solicitud").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Listado>().Property(x => x.Ranking).HasColumnName(@"Ranking").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Listado>().Property(x => x.Cliente).HasColumnName(@"Cliente").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Listado>().Property(x => x.Fecha).HasColumnName(@"Fecha").ValueGeneratedNever();
            modelBuilder.Entity<Listado>().Property(x => x.Recibo).HasColumnName(@"Recibo").ValueGeneratedNever().HasMaxLength(255);
            modelBuilder.Entity<Listado>().Property(x => x.Total).HasColumnName(@"Total").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Listado>().Property(x => x.Codigo).HasColumnName(@"Codigo").ValueGeneratedNever().HasMaxLength(255);
        }

        partial void CustomizeListadoMapping(ModelBuilder modelBuilder);

        #endregion

        #region Mcaja Mapping

        private void McajaMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Mcaja>().ToTable(@"Mcaja");
            modelBuilder.Entity<Mcaja>().Property(x => x.Idcaja).HasColumnName(@"Idcaja").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<Mcaja>().Property(x => x.Codcaja).HasColumnName(@"Codcaja").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<Mcaja>().Property(x => x.Codagencia).HasColumnName(@"Codagencia").ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<Mcaja>().Property(x => x.Fecha).HasColumnName(@"Fecha").ValueGeneratedNever();
            modelBuilder.Entity<Mcaja>().Property(x => x.Sinicial).HasColumnName(@"Sinicial").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Mcaja>().Property(x => x.Entrada).HasColumnName(@"Entrada").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Mcaja>().Property(x => x.Salida).HasColumnName(@"Salida").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Mcaja>().Property(x => x.Sfinal).HasColumnName(@"Sfinal").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<Mcaja>().Property(x => x.Estado).HasColumnName(@"Estado").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Mcaja>().HasKey(@"Idcaja");
        }

        partial void CustomizeMcajaMapping(ModelBuilder modelBuilder);

        #endregion

        #region Moneda Mapping

        private void MonedaMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Moneda>().ToTable(@"Moneda");
            modelBuilder.Entity<Moneda>().Property(x => x.Codmoneda).HasColumnName(@"Codmoneda").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<Moneda>().Property(x => x.Descripcion).HasColumnName(@"Descripcion").ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<Moneda>().Property(x => x.Simbolo).HasColumnName(@"Simbolo").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Moneda>().Property(x => x.Fecha).HasColumnName(@"Fecha").ValueGeneratedNever();
            modelBuilder.Entity<Moneda>().Property(x => x.Default).HasColumnName(@"Default").ValueGeneratedNever().HasDefaultValueSql(@"0");
            modelBuilder.Entity<Moneda>().HasKey(@"Codmoneda");
        }

        partial void CustomizeMonedaMapping(ModelBuilder modelBuilder);

        #endregion

        #region Movcaja Mapping

        private void MovcajaMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Movcaja>().ToTable(@"Movcaja");
            modelBuilder.Entity<Movcaja>().Property(x => x.Idmov).HasColumnName(@"Idmov").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<Movcaja>().Property(x => x.Descripcion).HasColumnName(@"Descripcion").IsRequired().ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<Movcaja>().Property(x => x.Codrubro).HasColumnName(@"Codrubro").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Movcaja>().HasKey(@"Idmov");
        }

        partial void CustomizeMovcajaMapping(ModelBuilder modelBuilder);

        #endregion

        #region PagosAdelantado Mapping

        private void PagosAdelantadoMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PagosAdelantado>().ToTable(@"PagosAdelantado");
            modelBuilder.Entity<PagosAdelantado>().Property(x => x.IdPagoefec).HasColumnName(@"IdPagoefec").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PagosAdelantado>().Property(x => x.Idingreso).HasColumnName(@"Idingreso").IsRequired().ValueGeneratedNever().HasMaxLength(14);
            modelBuilder.Entity<PagosAdelantado>().Property(x => x.Codagencia).HasColumnName(@"Codagencia").ValueGeneratedNever().HasMaxLength(4);
            modelBuilder.Entity<PagosAdelantado>().Property(x => x.FechaopParcial).HasColumnName(@"FechaopParcial").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<PagosAdelantado>().Property(x => x.ValorParcialpagado).HasColumnName(@"ValorParcialpagado").HasColumnType(@"decimal(11,2)").IsRequired().ValueGeneratedNever().HasPrecision(11, 2);
            modelBuilder.Entity<PagosAdelantado>().Property(x => x.Usuario).HasColumnName(@"Usuario").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<PagosAdelantado>().Property(x => x.HoraOp).HasColumnName(@"HoraOp").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<PagosAdelantado>().Property(x => x.EstadoOp).HasColumnName(@"EstadoOp").IsRequired().ValueGeneratedNever().HasMaxLength(3);
            modelBuilder.Entity<PagosAdelantado>().Property(x => x.CajaRegadel).HasColumnName(@"CajaRegadel").ValueGeneratedNever().HasMaxLength(8);
            modelBuilder.Entity<PagosAdelantado>().HasKey(@"IdPagoefec");
        }

        partial void CustomizePagosAdelantadoMapping(ModelBuilder modelBuilder);

        #endregion

        #region Pica Mapping

        private void PicaMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Pica>().ToTable(@"Pica");
            modelBuilder.Entity<Pica>().Property(x => x.Codcliente).HasColumnName(@"Codcliente").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<Pica>().Property(x => x.NombreEntidad).HasColumnName(@"NombreEntidad").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Pica>().Property(x => x.TipoRelacion).HasColumnName(@"TipoRelacion").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Pica>().Property(x => x.TiempoMantener).HasColumnName(@"TiempoMantener").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Pica>().Property(x => x.IngresoMensual).HasColumnName(@"IngresoMensual").HasColumnType(@"decimal(19,4)").ValueGeneratedNever().HasPrecision(19, 4);
            modelBuilder.Entity<Pica>().HasKey(@"Codcliente");
        }

        partial void CustomizePicaMapping(ModelBuilder modelBuilder);

        #endregion

        #region PrecioKilate Mapping

        private void PrecioKilateMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PrecioKilate>().ToTable(@"PrecioKilate");
            modelBuilder.Entity<PrecioKilate>().Property(x => x.DescKilate).HasColumnName(@"DescKilate").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<PrecioKilate>().Property(x => x.KilatePeso).HasColumnName(@"KilatePeso").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<PrecioKilate>().Property(x => x.PrecioKilate1).HasColumnName(@"PrecioKilate1").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<PrecioKilate>().HasKey(@"DescKilate");
        }

        partial void CustomizePrecioKilateMapping(ModelBuilder modelBuilder);

        #endregion

        #region Precio Mapping

        private void PrecioMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Precio>().ToTable(@"Precio");
            modelBuilder.Entity<Precio>().Property(x => x.Codcliente).HasColumnName(@"Codcliente").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<Precio>().Property(x => x.Kilate).HasColumnName(@"Kilate").HasColumnType(@"decimal(12,2)").IsRequired().ValueGeneratedNever().HasPrecision(12, 2);
            modelBuilder.Entity<Precio>().Property(x => x.Precio1).HasColumnName(@"Precio1").HasColumnType(@"decimal(12,2)").IsRequired().ValueGeneratedNever().HasPrecision(12, 2);
            modelBuilder.Entity<Precio>().Property(x => x.Gramos).HasColumnName(@"Gramos").HasColumnType(@"decimal(12,3)").IsRequired().ValueGeneratedNever().HasPrecision(12, 3);
            modelBuilder.Entity<Precio>().Property(x => x.PrecioOro).HasColumnName(@"PrecioOro").HasColumnType(@"decimal(12,3)").IsRequired().ValueGeneratedNever().HasPrecision(12, 3);
            modelBuilder.Entity<Precio>().HasKey(@"Codcliente", @"Kilate");
        }

        partial void CustomizePrecioMapping(ModelBuilder modelBuilder);

        #endregion

        #region ReporteCaja Mapping

        private void ReporteCajaMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ReporteCaja>().HasNoKey();
            modelBuilder.Entity<ReporteCaja>().ToView(@"ReporteCaja");
            modelBuilder.Entity<ReporteCaja>().Property(x => x.Codagencia).HasColumnName(@"Codagencia").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<ReporteCaja>().Property(x => x.Codrubro).HasColumnName(@"Codrubro").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<ReporteCaja>().Property(x => x.Codoperador).HasColumnName(@"Codoperador").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<ReporteCaja>().Property(x => x.Monto).HasColumnName(@"Monto").HasColumnType(@"decimal(19,4)").IsRequired().ValueGeneratedNever().HasPrecision(19, 4);
            modelBuilder.Entity<ReporteCaja>().Property(x => x.Fecha).HasColumnName(@"Fecha").IsRequired().ValueGeneratedNever();
        }

        partial void CustomizeReporteCajaMapping(ModelBuilder modelBuilder);

        #endregion

        #region Rubro Mapping

        private void RubroMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Rubro>().ToTable(@"Rubro");
            modelBuilder.Entity<Rubro>().Property(x => x.Codrubro).HasColumnName(@"Codrubro").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<Rubro>().Property(x => x.Descrubro).HasColumnName(@"Descrubro").IsRequired().ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<Rubro>().Property(x => x.Naturaleza).HasColumnName(@"Naturaleza").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Rubro>().HasKey(@"Codrubro");
        }

        partial void CustomizeRubroMapping(ModelBuilder modelBuilder);

        #endregion

        #region RubrosCaja Mapping

        private void RubrosCajaMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<RubrosCaja>().HasNoKey();
            modelBuilder.Entity<RubrosCaja>().ToView(@"RubrosCaja");
            modelBuilder.Entity<RubrosCaja>().Property(x => x.Rucodrub).HasColumnName(@"Rucodrub").IsRequired().ValueGeneratedNever().HasMaxLength(2);
            modelBuilder.Entity<RubrosCaja>().Property(x => x.Rucodope).HasColumnName(@"Rucodope").IsRequired().ValueGeneratedNever().HasMaxLength(2);
            modelBuilder.Entity<RubrosCaja>().Property(x => x.Rudescri).HasColumnName(@"Rudescri").IsRequired().ValueGeneratedNever().HasMaxLength(60);
            modelBuilder.Entity<RubrosCaja>().Property(x => x.Rudeha).HasColumnName(@"Rudeha").IsRequired().ValueGeneratedNever().HasMaxLength(1);
        }

        partial void CustomizeRubrosCajaMapping(ModelBuilder modelBuilder);

        #endregion

        #region TipoCambio Mapping

        private void TipoCambioMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TipoCambio>().ToTable(@"TipoCambio");
            modelBuilder.Entity<TipoCambio>().Property(x => x.Fecha).HasColumnName(@"Fecha").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<TipoCambio>().Property(x => x.Tipocambio).HasColumnName(@"Tipocambio").HasColumnType(@"decimal(12,4)").IsRequired().ValueGeneratedNever().HasPrecision(12, 4);
            modelBuilder.Entity<TipoCambio>().Property(x => x.Hora).HasColumnName(@"Hora").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<TipoCambio>().Property(x => x.PrecioOro).HasColumnName(@"PrecioOro").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<TipoCambio>().HasKey(@"Fecha");
        }

        partial void CustomizeTipoCambioMapping(ModelBuilder modelBuilder);

        #endregion

        #region TipoPreciosPagado Mapping

        private void TipoPreciosPagadoMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TipoPreciosPagado>().ToTable(@"TipoPreciosPagado");
            modelBuilder.Entity<TipoPreciosPagado>().Property(x => x.Codprecio).HasColumnName(@"Codprecio").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<TipoPreciosPagado>().Property(x => x.Descripcion).HasColumnName(@"Descripcion").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<TipoPreciosPagado>().Property(x => x.Pesoinicial).HasColumnName(@"Pesoinicial").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<TipoPreciosPagado>().Property(x => x.Pesofinal).HasColumnName(@"Pesofinal").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<TipoPreciosPagado>().HasKey(@"Codprecio");
        }

        partial void CustomizeTipoPreciosPagadoMapping(ModelBuilder modelBuilder);

        #endregion

        #region Tmpprecio Mapping

        private void TmpprecioMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Tmpprecio>().ToTable(@"Tmpprecio");
            modelBuilder.Entity<Tmpprecio>().Property(x => x.Codcierre).HasColumnName(@"Codcierre").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Tmpprecio>().Property(x => x.Linea).HasColumnName(@"Linea").IsRequired().ValueGeneratedNever().HasPrecision(3, 0);
            modelBuilder.Entity<Tmpprecio>().Property(x => x.Codcliente).HasColumnName(@"Codcliente").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<Tmpprecio>().Property(x => x.Cantidad).HasColumnName(@"Cantidad").HasColumnType(@"decimal(12,3)").IsRequired().ValueGeneratedNever().HasPrecision(12, 3);
            modelBuilder.Entity<Tmpprecio>().Property(x => x.Fecha).HasColumnName(@"Fecha").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Tmpprecio>().HasKey(@"Codcierre", @"Linea");
        }

        partial void CustomizeTmpprecioMapping(ModelBuilder modelBuilder);

        #endregion

        #region Usuario Mapping

        private void UsuarioMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Usuario>().ToTable(@"Usuario");
            modelBuilder.Entity<Usuario>().Property(x => x.Codoperador).HasColumnName(@"Codoperador").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<Usuario>().Property(x => x.Username).HasColumnName(@"Username").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Usuario>().Property(x => x.Clave).HasColumnName(@"Clave").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<Usuario>().Property(x => x.Nombre).HasColumnName(@"Nombre").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<Usuario>().Property(x => x.Pregunta).HasColumnName(@"Pregunta").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Usuario>().Property(x => x.Respuesta).HasColumnName(@"Respuesta").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Usuario>().Property(x => x.Fcreau).HasColumnName(@"Fcreau").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<Usuario>().Property(x => x.Nivel).HasColumnName(@"Nivel").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<Usuario>().Property(x => x.Estado).HasColumnName(@"Estado").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<Usuario>().HasKey(@"Codoperador");
        }

        partial void CustomizeUsuarioMapping(ModelBuilder modelBuilder);

        #endregion

        #region ComprasOperador Mapping

        private void ComprasOperadorMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ComprasOperador>().HasNoKey();
            modelBuilder.Entity<ComprasOperador>().ToView(@"ComprasOperador");
            modelBuilder.Entity<ComprasOperador>().Property(x => x.Nombre).HasColumnName(@"Nombre").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<ComprasOperador>().Property(x => x.Numcompra).HasColumnName(@"Numcompra").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<ComprasOperador>().Property(x => x.Fecha).HasColumnName(@"Fecha").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<ComprasOperador>().Property(x => x.PesoTotal).HasColumnName(@"PesoTotal").HasColumnType(@"decimal(11,2)").IsRequired().ValueGeneratedNever().HasPrecision(11, 2);
            modelBuilder.Entity<ComprasOperador>().Property(x => x.Total).HasColumnName(@"Total").HasColumnType(@"decimal(15,2)").IsRequired().ValueGeneratedNever().HasPrecision(15, 2);
            modelBuilder.Entity<ComprasOperador>().Property(x => x.Codcaja).HasColumnName(@"Codcaja").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<ComprasOperador>().Property(x => x.Hora).HasColumnName(@"Hora").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<ComprasOperador>().Property(x => x.Kilate).HasColumnName(@"Kilate").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<ComprasOperador>().Property(x => x.Peso).HasColumnName(@"Peso").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<ComprasOperador>().Property(x => x.Importe).HasColumnName(@"Importe").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<ComprasOperador>().Property(x => x.Preciok).HasColumnName(@"Preciok").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<ComprasOperador>().Property(x => x.Codcliente).HasColumnName(@"Codcliente").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<ComprasOperador>().Property(x => x.Codagencia).HasColumnName(@"Codagencia").IsRequired().ValueGeneratedNever().HasMaxLength(10);
        }

        partial void CustomizeComprasOperadorMapping(ModelBuilder modelBuilder);

        #endregion

        #region MovimientosCajaSelect Mapping

        private void MovimientosCajaSelectMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MovimientosCajaSelect>().HasNoKey();
            modelBuilder.Entity<MovimientosCajaSelect>().ToView(@"MovimientosCajaSelect");
            modelBuilder.Entity<MovimientosCajaSelect>().Property(x => x.Estado).HasColumnName(@"estado").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<MovimientosCajaSelect>().Property(x => x.Codcaja).HasColumnName(@"codcaja").HasColumnType(@"nvarchar(10)").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<MovimientosCajaSelect>().Property(x => x.Hora).HasColumnName(@"hora").HasColumnType(@"nvarchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<MovimientosCajaSelect>().Property(x => x.Fecha).HasColumnName(@"fecha").HasColumnType(@"datetime2").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<MovimientosCajaSelect>().Property(x => x.Concepto).HasColumnName(@"concepto").HasColumnType(@"nvarchar(250)").ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<MovimientosCajaSelect>().Property(x => x.Efectivo).HasColumnName(@"efectivo").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<MovimientosCajaSelect>().Property(x => x.Cheque).HasColumnName(@"cheque").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<MovimientosCajaSelect>().Property(x => x.Transferencia).HasColumnName(@"transferencia").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
        }

        partial void CustomizeMovimientosCajaSelectMapping(ModelBuilder modelBuilder);

        #endregion

        #region TransaccionEfectivo Mapping

        private void TransaccionEfectivoMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TransaccionEfectivo>().HasNoKey();
            modelBuilder.Entity<TransaccionEfectivo>().ToView(@"TransaccionEfectivo");
            modelBuilder.Entity<TransaccionEfectivo>().Property(x => x.Numcompra1).HasColumnName(@"Numcompra1").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<TransaccionEfectivo>().Property(x => x.Codcliente1).HasColumnName(@"Codcliente1").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<TransaccionEfectivo>().Property(x => x.Nombres1).HasColumnName(@"Nombres1").IsRequired().ValueGeneratedNever().HasMaxLength(35);
            modelBuilder.Entity<TransaccionEfectivo>().Property(x => x.Apellidos1).HasColumnName(@"Apellidos1").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<TransaccionEfectivo>().Property(x => x.Fecha1).HasColumnName(@"Fecha1").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<TransaccionEfectivo>().Property(x => x.Total1).HasColumnName(@"Total1").HasColumnType(@"decimal(15,2)").IsRequired().ValueGeneratedNever().HasPrecision(15, 2);
            modelBuilder.Entity<TransaccionEfectivo>().Property(x => x.FormaPago).HasColumnName(@"FormaPago").IsRequired().ValueGeneratedNever().HasMaxLength(13);
        }

        partial void CustomizeTransaccionEfectivoMapping(ModelBuilder modelBuilder);

        #endregion

        #region TipoDocumento Mapping

        private void TipoDocumentoMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TipoDocumento>().ToTable(@"TipoDocumento");
            modelBuilder.Entity<TipoDocumento>().Property(x => x.Idtipodocumento).HasColumnName(@"Idtipodocumento").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<TipoDocumento>().Property(x => x.Nombre).HasColumnName(@"Nombre").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<TipoDocumento>().Property(x => x.Simbolo).HasColumnName(@"Simbolo").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<TipoDocumento>().HasKey(@"Idtipodocumento");
        }

        partial void CustomizeTipoDocumentoMapping(ModelBuilder modelBuilder);

        #endregion

        #region TipoPrecio Mapping

        private void TipoPrecioMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TipoPrecio>().ToTable(@"TipoPrecio");
            modelBuilder.Entity<TipoPrecio>().Property(x => x.Idtipoprecio).HasColumnName(@"Idtipoprecio").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<TipoPrecio>().Property(x => x.Descripcion).HasColumnName(@"Descripcion").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<TipoPrecio>().Property(x => x.Precio).HasColumnName(@"Precio").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<TipoPrecio>().HasKey(@"Idtipoprecio");
        }

        partial void CustomizeTipoPrecioMapping(ModelBuilder modelBuilder);

        #endregion

        #region ComprasOperador1 Mapping

        private void ComprasOperador1Mapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ComprasOperador1>().HasNoKey();
            modelBuilder.Entity<ComprasOperador1>().ToView(@"ComprasOperador1");
            modelBuilder.Entity<ComprasOperador1>().Property(x => x.Nombre).HasColumnName(@"Nombre").IsRequired().ValueGeneratedNever().HasMaxLength(100);
            modelBuilder.Entity<ComprasOperador1>().Property(x => x.Numcompra).HasColumnName(@"Numcompra").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<ComprasOperador1>().Property(x => x.Fecha).HasColumnName(@"Fecha").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<ComprasOperador1>().Property(x => x.PesoTotal).HasColumnName(@"PesoTotal").HasColumnType(@"decimal(11,2)").IsRequired().ValueGeneratedNever().HasPrecision(11, 2);
            modelBuilder.Entity<ComprasOperador1>().Property(x => x.Total).HasColumnName(@"Total").HasColumnType(@"decimal(15,2)").IsRequired().ValueGeneratedNever().HasPrecision(15, 2);
            modelBuilder.Entity<ComprasOperador1>().Property(x => x.Codcaja).HasColumnName(@"Codcaja").IsRequired().ValueGeneratedNever().HasMaxLength(10);
            modelBuilder.Entity<ComprasOperador1>().Property(x => x.Hora).HasColumnName(@"Hora").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<ComprasOperador1>().Property(x => x.Kilate).HasColumnName(@"Kilate").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<ComprasOperador1>().Property(x => x.Peso).HasColumnName(@"Peso").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<ComprasOperador1>().Property(x => x.Importe).HasColumnName(@"Importe").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<ComprasOperador1>().Property(x => x.Preciok).HasColumnName(@"Preciok").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<ComprasOperador1>().Property(x => x.Codcliente).HasColumnName(@"Codcliente").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<ComprasOperador1>().Property(x => x.Codagencia).HasColumnName(@"Codagencia").IsRequired().ValueGeneratedNever().HasMaxLength(10);
        }

        partial void CustomizeComprasOperador1Mapping(ModelBuilder modelBuilder);

        #endregion

        #region DescargueByCompra Mapping

        private void DescargueByCompraMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DescargueByCompra>().HasNoKey();
            modelBuilder.Entity<DescargueByCompra>().ToView(@"DescargueByCompra");
            modelBuilder.Entity<DescargueByCompra>().Property(x => x.Dgnumdes).HasColumnName(@"Dgnumdes").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<DescargueByCompra>().Property(x => x.Dgfecdes).HasColumnName(@"Dgfecdes").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<DescargueByCompra>().Property(x => x.Numcompra).HasColumnName(@"Numcompra").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<DescargueByCompra>().Property(x => x.Fecha).HasColumnName(@"Fecha").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<DescargueByCompra>().Property(x => x.Codcliente).HasColumnName(@"Codcliente").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<DescargueByCompra>().Property(x => x.Nombres).HasColumnName(@"Nombres").IsRequired().ValueGeneratedNever().HasMaxLength(35);
            modelBuilder.Entity<DescargueByCompra>().Property(x => x.Apellidos).HasColumnName(@"Apellidos").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<DescargueByCompra>().Property(x => x.Peso).HasColumnName(@"Peso").HasColumnType(@"decimal(11,2)").IsRequired().ValueGeneratedNever().HasPrecision(11, 2);
            modelBuilder.Entity<DescargueByCompra>().Property(x => x.Total).HasColumnName(@"Total").HasColumnType(@"decimal(15,2)").IsRequired().ValueGeneratedNever().HasPrecision(15, 2);
            modelBuilder.Entity<DescargueByCompra>().Property(x => x.Cantcompra).HasColumnName(@"Cantcompra").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
        }

        partial void CustomizeDescargueByCompraMapping(ModelBuilder modelBuilder);

        #endregion

        #region VVariacionesCliente Mapping

        private void VVariacionesClienteMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<VVariacionesCliente>().HasNoKey();
            modelBuilder.Entity<VVariacionesCliente>().ToView(@"VVariacionesCliente");
            modelBuilder.Entity<VVariacionesCliente>().Property(x => x.Codcliente).HasColumnName(@"Codcliente").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<VVariacionesCliente>().Property(x => x.Nombres).HasColumnName(@"Nombres").IsRequired().ValueGeneratedNever().HasMaxLength(35);
            modelBuilder.Entity<VVariacionesCliente>().Property(x => x.Apellidos).HasColumnName(@"Apellidos").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<VVariacionesCliente>().Property(x => x.Mes).HasColumnName(@"Mes").ValueGeneratedNever().HasMaxLength(30);
            modelBuilder.Entity<VVariacionesCliente>().Property(x => x.Monto).HasColumnName(@"Monto").HasColumnType(@"decimal(32,8)").ValueGeneratedNever().HasPrecision(32, 8);
            modelBuilder.Entity<VVariacionesCliente>().Property(x => x.MontoMensual).HasColumnName(@"MontoMensual").HasColumnType(@"decimal(38,2)").ValueGeneratedNever().HasPrecision(38, 2);
            modelBuilder.Entity<VVariacionesCliente>().Property(x => x.Variacion).HasColumnName(@"Variacion").HasColumnType(@"decimal(38,6)").ValueGeneratedNever().HasPrecision(38, 6);
            modelBuilder.Entity<VVariacionesCliente>().Property(x => x.Fecha).HasColumnName(@"Fecha").IsRequired().ValueGeneratedNever();
        }

        partial void CustomizeVVariacionesClienteMapping(ModelBuilder modelBuilder);

        #endregion

        #region DetalleCompra Mapping

        private void DetalleCompraMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DetalleCompra>().HasNoKey();
            modelBuilder.Entity<DetalleCompra>().ToView(@"DetalleCompra", @"dbo");
            modelBuilder.Entity<DetalleCompra>().Property(x => x.TipoDocumento).HasColumnName(@"TipoDocumento").HasColumnType(@"nvarchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.SimboloMoneda).HasColumnName(@"SimboloMoneda").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.Codcliente).HasColumnName(@"Codcliente").HasColumnType(@"nvarchar(20)").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.Nombres).HasColumnName(@"Nombres").HasColumnType(@"nvarchar(35)").IsRequired().ValueGeneratedNever().HasMaxLength(35);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.Apellidos).HasColumnName(@"Apellidos").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.Numcedula).HasColumnName(@"Numcedula").HasColumnType(@"nvarchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.Celular).HasColumnName(@"Celular").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.Email).HasColumnName(@"Email").HasColumnType(@"nvarchar(50)").ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.Idtipodocumento).HasColumnName(@"Idtipodocumento").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.Numcompra).HasColumnName(@"Numcompra").HasColumnType(@"nvarchar(20)").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.Peso).HasColumnName(@"Peso").HasColumnType(@"decimal(11,2)").IsRequired().ValueGeneratedNever().HasPrecision(11, 2);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.Total).HasColumnName(@"Total").HasColumnType(@"decimal(15,2)").IsRequired().ValueGeneratedNever().HasPrecision(15, 2);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.FechaCompra).HasColumnName(@"FechaCompra").HasColumnType(@"datetime2").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<DetalleCompra>().Property(x => x.Codestado).HasColumnName(@"Codestado").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.Hora).HasColumnName(@"Hora").HasColumnType(@"nvarchar(50)").IsRequired().ValueGeneratedNever().HasMaxLength(50);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.Nocontrato).HasColumnName(@"Nocontrato").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.Linea).HasColumnName(@"Linea").HasColumnType(@"int").IsRequired().ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.Descripcion).HasColumnName(@"Descripcion").HasColumnType(@"nvarchar(250)").IsRequired().ValueGeneratedNever().HasMaxLength(250);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.Kilate).HasColumnName(@"Kilate").HasColumnType(@"nvarchar(20)").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.PrecioItem).HasColumnName(@"PrecioItem").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.PesoItem).HasColumnName(@"PesoItem").HasColumnType(@"decimal(18,2)").IsRequired().ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.ImporteItem).HasColumnName(@"ImporteItem").HasColumnType(@"decimal(18,2)").ValueGeneratedNever().HasPrecision(18, 2);
            modelBuilder.Entity<DetalleCompra>().Property(x => x.Direccion).HasColumnName(@"Direccion").HasColumnType(@"varchar(max)").IsRequired().ValueGeneratedNever();
            modelBuilder.Entity<DetalleCompra>().Property(x => x.Logo).HasColumnName(@"Logo").HasColumnType(@"varbinary(max)").ValueGeneratedNever();
        }

        partial void CustomizeDetalleCompraMapping(ModelBuilder modelBuilder);

        #endregion

        private void RelationshipsMapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Adelanto>().HasOne(x => x.Cliente).WithMany(op => op.Adelantos).HasForeignKey(@"Codcliente").IsRequired(true);
            modelBuilder.Entity<Adelanto>().HasOne(x => x.Compra).WithMany(op => op.Adelantos1).HasForeignKey(@"Numcompra").IsRequired(true);

            modelBuilder.Entity<Agencia>().HasMany(x => x.Compras).WithOne(op => op.Agencia).HasForeignKey(@"Codagencia").IsRequired(true);
            modelBuilder.Entity<Agencia>().HasMany(x => x.Mcajas).WithOne(op => op.Agencia).HasForeignKey(@"Codagencia").IsRequired(false);

            modelBuilder.Entity<Caja>().HasMany(x => x.Compras).WithOne(op => op.Caja).HasForeignKey(@"Codcaja").IsRequired(true);
            modelBuilder.Entity<Caja>().HasMany(x => x.Mcajas).WithOne(op => op.Caja).HasForeignKey(@"Codcaja").IsRequired(true);

            modelBuilder.Entity<Cliente>().HasMany(x => x.Adelantos).WithOne(op => op.Cliente).HasForeignKey(@"Codcliente").IsRequired(true);
            modelBuilder.Entity<Cliente>().HasMany(x => x.Compras).WithOne(op => op.Cliente).HasForeignKey(@"Codcliente").IsRequired(true);
            modelBuilder.Entity<Cliente>().HasOne(x => x.TipoDocumento).WithMany(op => op.Clientes).HasForeignKey(@"Idtipodocumento").IsRequired(false);

            modelBuilder.Entity<Compra>().HasMany(x => x.Adelantos1).WithOne(op => op.Compra).HasForeignKey(@"Numcompra").IsRequired(true);
            modelBuilder.Entity<Compra>().HasOne(x => x.Cliente).WithMany(op => op.Compras).HasForeignKey(@"Codcliente").IsRequired(true);
            modelBuilder.Entity<Compra>().HasOne(x => x.Moneda).WithMany(op => op.Compras).HasForeignKey(@"Codmoneda").IsRequired(true);
            modelBuilder.Entity<Compra>().HasOne(x => x.Agencia).WithMany(op => op.Compras).HasForeignKey(@"Codagencia").IsRequired(true);
            modelBuilder.Entity<Compra>().HasOne(x => x.Usuario1).WithMany(op => op.Compras).HasForeignKey(@"Usuario").IsRequired(true);
            modelBuilder.Entity<Compra>().HasOne(x => x.Caja).WithMany(op => op.Compras).HasForeignKey(@"Codcaja").IsRequired(true);
            modelBuilder.Entity<Compra>().HasOne(x => x.Descargue).WithMany(op => op.Compras).HasForeignKey(@"Dgnumdes").IsRequired(false);
            modelBuilder.Entity<Compra>().HasMany(x => x.ComprasAdelantos).WithOne(op => op.Compra).HasForeignKey(@"Numcompra").IsRequired(true);
            modelBuilder.Entity<Compra>().HasMany(x => x.DetCompras).WithOne(op => op.Compra).HasForeignKey(@"Numcompra").IsRequired(true);

            modelBuilder.Entity<ComprasAdelanto>().HasOne(x => x.Compra).WithMany(op => op.ComprasAdelantos).HasForeignKey(@"Numcompra").IsRequired(true);

            modelBuilder.Entity<Descargue>().HasMany(x => x.Compras).WithOne(op => op.Descargue).HasForeignKey(@"Dgnumdes").IsRequired(false);

            modelBuilder.Entity<DetCompra>().HasOne(x => x.Compra).WithMany(op => op.DetCompras).HasForeignKey(@"Numcompra").IsRequired(true);

            modelBuilder.Entity<Detacaja>().HasOne(x => x.Mcaja).WithMany(op => op.Detacajas).HasForeignKey(@"Idcaja").IsRequired(true);
            modelBuilder.Entity<Detacaja>().HasOne(x => x.Movcaja).WithMany(op => op.Detacajas).HasForeignKey(@"Idmov").IsRequired(true);

            modelBuilder.Entity<Mcaja>().HasMany(x => x.Detacajas).WithOne(op => op.Mcaja).HasForeignKey(@"Idcaja").IsRequired(true);
            modelBuilder.Entity<Mcaja>().HasOne(x => x.Agencia).WithMany(op => op.Mcajas).HasForeignKey(@"Codagencia").IsRequired(false);
            modelBuilder.Entity<Mcaja>().HasOne(x => x.Caja).WithMany(op => op.Mcajas).HasForeignKey(@"Codcaja").IsRequired(true);

            modelBuilder.Entity<Moneda>().HasMany(x => x.Compras).WithOne(op => op.Moneda).HasForeignKey(@"Codmoneda").IsRequired(true);

            modelBuilder.Entity<Movcaja>().HasMany(x => x.Detacajas).WithOne(op => op.Movcaja).HasForeignKey(@"Idmov").IsRequired(true);
            modelBuilder.Entity<Movcaja>().HasOne(x => x.Rubro).WithMany(op => op.Movcajas).HasForeignKey(@"Codrubro").IsRequired(false);

            modelBuilder.Entity<Rubro>().HasMany(x => x.Movcajas).WithOne(op => op.Rubro).HasForeignKey(@"Codrubro").IsRequired(false);

            modelBuilder.Entity<Usuario>().HasMany(x => x.Compras).WithOne(op => op.Usuario1).HasForeignKey(@"Usuario").IsRequired(true);

            modelBuilder.Entity<TipoDocumento>().HasMany(x => x.Clientes).WithOne(op => op.TipoDocumento).HasForeignKey(@"Idtipodocumento").IsRequired(false);
        }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        public bool HasChanges()
        {
            return ChangeTracker.Entries().Any(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added || e.State == Microsoft.EntityFrameworkCore.EntityState.Modified || e.State == Microsoft.EntityFrameworkCore.EntityState.Deleted);
        }

        partial void OnCreated();
    }
}
