//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 27/7/2025 7:04:52 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace SistemaOro.Data.Entities
{
    public partial class ViewComprasOnza : INotifyPropertyChanging, INotifyPropertyChanged {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private string _Codcaja;

        private string? _Codagencia;

        private string _Numcompra;

        private string _Codcliente;

        private int? _Lectura;

        private int _Codmoneda;

        private string? _Simbolo;

        private string _Nombres;

        private string? _Apellidos;

        private decimal? _Kilate;

        private decimal _Peso;

        private decimal _Preciok;

        private decimal? _Importe;

        private decimal _Total;

        private DateTime? _Fecha;

        private decimal? _Tipocambio;

        private decimal? _PrecioOro;

        private decimal? _VMargen;

        private decimal? _PrecioKilate;

        private decimal? _Onzas;

        private int _MonedaLocal;

        public ViewComprasOnza()
        {
            OnCreated();
        }

        public string Codcaja
        {
            get
            {
                return this._Codcaja;
            }
            set
            {
                if (this._Codcaja != value)
                {
                    this.SendPropertyChanging("Codcaja");
                    this._Codcaja = value;
                    this.SendPropertyChanged("Codcaja");
                }
            }
        }

        public string? Codagencia
        {
            get
            {
                return this._Codagencia;
            }
            set
            {
                if (this._Codagencia != value)
                {
                    this.SendPropertyChanging("Codagencia");
                    this._Codagencia = value;
                    this.SendPropertyChanged("Codagencia");
                }
            }
        }

        public string Numcompra
        {
            get
            {
                return this._Numcompra;
            }
            set
            {
                if (this._Numcompra != value)
                {
                    this.SendPropertyChanging("Numcompra");
                    this._Numcompra = value;
                    this.SendPropertyChanged("Numcompra");
                }
            }
        }

        public string Codcliente
        {
            get
            {
                return this._Codcliente;
            }
            set
            {
                if (this._Codcliente != value)
                {
                    this.SendPropertyChanging("Codcliente");
                    this._Codcliente = value;
                    this.SendPropertyChanged("Codcliente");
                }
            }
        }

        public int? Lectura
        {
            get
            {
                return this._Lectura;
            }
            set
            {
                if (this._Lectura != value)
                {
                    this.SendPropertyChanging("Lectura");
                    this._Lectura = value;
                    this.SendPropertyChanged("Lectura");
                }
            }
        }

        public int Codmoneda
        {
            get
            {
                return this._Codmoneda;
            }
            set
            {
                if (this._Codmoneda != value)
                {
                    this.SendPropertyChanging("Codmoneda");
                    this._Codmoneda = value;
                    this.SendPropertyChanged("Codmoneda");
                }
            }
        }

        public string? Simbolo
        {
            get
            {
                return this._Simbolo;
            }
            set
            {
                if (this._Simbolo != value)
                {
                    this.SendPropertyChanging("Simbolo");
                    this._Simbolo = value;
                    this.SendPropertyChanged("Simbolo");
                }
            }
        }

        public string Nombres
        {
            get
            {
                return this._Nombres;
            }
            set
            {
                if (this._Nombres != value)
                {
                    this.SendPropertyChanging("Nombres");
                    this._Nombres = value;
                    this.SendPropertyChanged("Nombres");
                }
            }
        }

        public string? Apellidos
        {
            get
            {
                return this._Apellidos;
            }
            set
            {
                if (this._Apellidos != value)
                {
                    this.SendPropertyChanging("Apellidos");
                    this._Apellidos = value;
                    this.SendPropertyChanged("Apellidos");
                }
            }
        }

        public decimal? Kilate
        {
            get
            {
                return this._Kilate;
            }
            set
            {
                if (this._Kilate != value)
                {
                    this.SendPropertyChanging("Kilate");
                    this._Kilate = value;
                    this.SendPropertyChanged("Kilate");
                }
            }
        }

        public decimal Peso
        {
            get
            {
                return this._Peso;
            }
            set
            {
                if (this._Peso != value)
                {
                    this.SendPropertyChanging("Peso");
                    this._Peso = value;
                    this.SendPropertyChanged("Peso");
                }
            }
        }

        public decimal Preciok
        {
            get
            {
                return this._Preciok;
            }
            set
            {
                if (this._Preciok != value)
                {
                    this.SendPropertyChanging("Preciok");
                    this._Preciok = value;
                    this.SendPropertyChanged("Preciok");
                }
            }
        }

        public decimal? Importe
        {
            get
            {
                return this._Importe;
            }
            set
            {
                if (this._Importe != value)
                {
                    this.SendPropertyChanging("Importe");
                    this._Importe = value;
                    this.SendPropertyChanged("Importe");
                }
            }
        }

        public decimal Total
        {
            get
            {
                return this._Total;
            }
            set
            {
                if (this._Total != value)
                {
                    this.SendPropertyChanging("Total");
                    this._Total = value;
                    this.SendPropertyChanged("Total");
                }
            }
        }

        public DateTime? Fecha
        {
            get
            {
                return this._Fecha;
            }
            set
            {
                if (this._Fecha != value)
                {
                    this.SendPropertyChanging("Fecha");
                    this._Fecha = value;
                    this.SendPropertyChanged("Fecha");
                }
            }
        }

        public decimal? Tipocambio
        {
            get
            {
                return this._Tipocambio;
            }
            set
            {
                if (this._Tipocambio != value)
                {
                    this.SendPropertyChanging("Tipocambio");
                    this._Tipocambio = value;
                    this.SendPropertyChanged("Tipocambio");
                }
            }
        }

        public decimal? PrecioOro
        {
            get
            {
                return this._PrecioOro;
            }
            set
            {
                if (this._PrecioOro != value)
                {
                    this.SendPropertyChanging("PrecioOro");
                    this._PrecioOro = value;
                    this.SendPropertyChanged("PrecioOro");
                }
            }
        }

        public decimal? VMargen
        {
            get
            {
                return this._VMargen;
            }
            set
            {
                if (this._VMargen != value)
                {
                    this.SendPropertyChanging("VMargen");
                    this._VMargen = value;
                    this.SendPropertyChanged("VMargen");
                }
            }
        }

        public decimal? PrecioKilate
        {
            get
            {
                return this._PrecioKilate;
            }
            set
            {
                if (this._PrecioKilate != value)
                {
                    this.SendPropertyChanging("PrecioKilate");
                    this._PrecioKilate = value;
                    this.SendPropertyChanged("PrecioKilate");
                }
            }
        }

        public decimal? Onzas
        {
            get
            {
                return this._Onzas;
            }
            set
            {
                if (this._Onzas != value)
                {
                    this.SendPropertyChanging("Onzas");
                    this._Onzas = value;
                    this.SendPropertyChanged("Onzas");
                }
            }
        }

        public int MonedaLocal
        {
            get
            {
                return this._MonedaLocal;
            }
            set
            {
                if (this._MonedaLocal != value)
                {
                    this.SendPropertyChanging("MonedaLocal");
                    this._MonedaLocal = value;
                    this.SendPropertyChanged("MonedaLocal");
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
