//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 13/4/2024 12:33 p. m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace SistemaOro.Data.Entities
{
    public sealed partial class Compra {

        public Compra()
        {
            this.SaldoAdelanto = 0m;
            this.ComprasAdelantos = new List<ComprasAdelanto>();
            this.DetCompras = new List<DetCompra>();
            this.Detacierres = new List<Detacierre>();
            OnCreated();
        }

        public string Numcompra { get; set; }

        public string Codagencia { get; set; }

        public string Codcliente { get; set; }

        public string Codcaja { get; set; }

        public decimal Peso { get; set; }

        public int Codmoneda { get; set; }

        public decimal Total { get; set; }

        public DateTime Fecha { get; set; }

        public int Codestado { get; set; }

        public string Usuario { get; set; }

        public string Hora { get; set; }

        public string FormaPago { get; set; }

        public int Dgnumdes { get; set; }

        public decimal Efectivo { get; set; }

        public decimal Cheque { get; set; }

        public decimal Transferencia { get; set; }

        public decimal PorCobrar { get; set; }

        public decimal PorPagar { get; set; }

        public decimal Adelantos { get; set; }

        public decimal SaldoPorPagar { get; set; }

        public decimal? SaldoAdelanto { get; set; }

        public decimal? SaldoAdelantoDolares { get; set; }

        public Agencia Agencia { get; set; }

        public Cliente Cliente { get; set; }

        public Caja Caja { get; set; }

        public Moneda Moneda { get; set; }

        public IList<ComprasAdelanto> ComprasAdelantos { get; set; }

        public IList<DetCompra> DetCompras { get; set; }

        public IList<Detacierre> Detacierres { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
