//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 28/7/2024 4:09:42 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace SistemaOro.Data.Entities
{
    public partial class Precio {

        public Precio()
        {
            OnCreated();
        }

        public string Codcliente { get; set; }

        public decimal Kilate { get; set; }

        public decimal Precio1 { get; set; }

        public decimal Gramos { get; set; }

        public decimal PrecioOro { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          Precio toCompare = obj as Precio;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.Codcliente, toCompare.Codcliente))
            return false;
          if (!Object.Equals(this.Kilate, toCompare.Kilate))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + Codcliente.GetHashCode();
          hashCode = (hashCode * 7) + Kilate.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
